### ISSUE TITLE
Cannot remove namespace from element

### ISSUE THREAD

**Issue by denisw** [libxmljs/libxmljs#133]
I want to remove the "xmlns" definition of a certain Element (from an Atom <entry> that is going to be added to a wrapper <feed>, to be exact), but the libxmljs API doesn't seem to offer that functionality. I tried element.namespace(null) but this only results in a segmentation fault.

**Comment by rc0x03** [comment]
The problem here seems to be that we're setting `xmlNode->ns` to NULL, but we're not freeing `xmlNode->nsDef`. This means that any namespace declarations on the node will still be there.

**Comment by rc0x03** [comment]
I think the proper way to remove a namespace would be to expose `node->namespaces()->remove()` in the API, instead of calling `node->namespaces(null)`.

This way users can remove individual namespaces or namespace declarations by calling `name->namespaces(true)->remove()`.

**Comment by Jollyfant** [comment]
Hi guys, was this ever solved? One namespace annoyingly keeps sticking to my element and I have to replace it out in the string representation of the XML.

**Comment by thybzi** [comment]
Seems that bug still exists.
I'm using something like this
```
            myElem.attr({
                xmlns: null,
            });
```
