### ISSUE TITLE
Can not use cdata

### ISSUE THREAD

**Issue by ashalaenko** [libxmljs/libxmljs#135]
Hi! How I can use cdata section? Code form example does not work. I tried to use el.node('...').cdata('...'); // like el.node('...').attr('') - but this not work. Please help!

**Comment by muratatak77** [comment]
generetion vast xml as a vast example
var temp_vast_xml = vast3_xml.node('VAST');
temp_vast_xml = temp_vast_xml.node('AdTitle', temp_vast_xml.cdata(AdTitle) );

**Comment by muratatak77** [comment]
Code :

var AdTitle = xmlDoc.get('//AdTitle').text();
temp_vast_xml = temp_vast_xml.node('AdTitle');
temp_vast_xml = temp_vast_xml.cdata(AdTitle);	
temp_vast_xml = temp_vast_xml.parent();
console.log("AdTitle : " , AdTitle);

View : 

<AdTitle>
         <![CDATA[Test Ad - Istikbal m3u8 ]]>
</AdTitle>
