### ISSUE TITLE
windows support

### ISSUE THREAD

**Issue by shimondoodkin** [libxmljs/libxmljs#176]
can you make a windows version for this? i have made xml2-config.bat
https://gist.github.com/4341933

i can't get the gyp to work

**Comment by q00u** [comment]
What happened to the vendor-src branch?

**Comment by dragonbanshee** [comment]
I don't know how relevant this is anymore, but running Windows 8.1 and Node 0.12.0, I am able to install this package via npm without any errors.

**Comment by BHare1985** [comment]
Running Windows 10 and Node 0.12.0 I have to supply `--msvs_version=2013`

**Comment by benoror** [comment]
@BHare1985 where do you make that change? I have a windows setup with compilation issues, I would like to confirm

**Comment by BHare1985** [comment]
Execute `npm install --msvs_version=2013`  .. 2013 works for me because i have visual studio 2013
