### ISSUE TITLE
EXSLT - Unable to use regexp:match

### ISSUE THREAD

**Issue by pvoisin** [libxmljs/libxmljs#185]
Hi!

I'm trying to use EXLST's regexp:match function but I'm ending up with a "xmlXPathCompOpEval: function match not found" error.

I also tried to include the regexp.xsl implementation offered on the site but I'm getting the very same thing at the end.

Is libxmljs supposed to support functions at `xmlns:regexp="http://exslt.org/regular-expressions"`? If not, how would it be achievable?

**Comment by mahairod** [comment]
Very strange: was closed without investigating. But root cause is probably missing plugin for libxslt which is used as dependency
