### ISSUE TITLE
Validating against multiple XSD's (<import> in XSD)

### ISSUE THREAD

**Issue by baconmania** [libxmljs/libxmljs#202]
Is there way to use libxmljs to validate a document against multiple XSD's? My XSD has several `<import>` statements, which I don't think libxmljs accounts for. So when I try to run a validation, I get "invalid XSD schema".

**Comment by schmod** [comment]
If anybody's stumbling across this issue years later, it appears that this has now been implemented -- `node-libxml-xsd` should no longer be necessary.

**Comment by rchipka** [comment]
@schmod can we close this issue?

**Comment by albanm** [comment]
If it has been implemented I would like to deprecate node-libxml-xsd and add a note in the README giving proper instructions.

I don't see an asynchronous version of XSD validation referenced in libxmljs's doc. Is there something ?

**Comment by schmod** [comment]
@rchipka This issue is already closed.

@albanm There's no asynchronous validation as far as I can tell.

This is the code I've used (which seems to work):

```js
const cwd = process.cwd();
try {
  process.chdir(path.dirname(schemaPath)); // This seems undesirable...
  const schema = libxml.parseXml(fs.readFileSync(schemaPath, 'utf8'));

  const doc = libxml.parseXml(document);
  const valid = doc.validate(schema);
  if (!valid) {
    console.error('XML did not validate against XSD schema!', { errors: doc.validationErrors });
  }
  return valid; 
} catch (e) {
  throw e;
} finally {
  process.chdir(cwd);
}
```

**Comment by albanm** [comment]
Ok, so the main reason behind node-libxml-xsd remains true. A I said in a previous message:

"Beware that if imports are resolved by libxml then the parsing of the schema becomes a IO bound task. So this synchronous implementation is not a very good fit."
