### ISSUE TITLE
Nodejs assertion fails when adding root cloned element w/ lots of nodes

### ISSUE THREAD

**Issue by ryeager** [libxmljs/libxmljs#214]
Hi,

I am trying to clone an XML node with 10k rows of this schema:

&lt;latency>
&nbsp;&nbsp;&lt;datapoint>
&nbsp;&nbsp;&nbsp;&nbsp;&lt;id>1&lt;/id>
&nbsp;&nbsp;&nbsp;&nbsp;&lt;min>5.6982e-05&lt;/min>
&nbsp;&nbsp;&nbsp;&nbsp;&lt;avg>5.6982e-05&lt;/avg>
&nbsp;&nbsp;&nbsp;&nbsp;&lt;max>5.6982e-05&lt;/max>
&nbsp;&nbsp;&nbsp;&nbsp;&lt;t>2011-01-18 14:30:40&lt;/t>
&nbsp;&nbsp;&lt;/datapoint>
&nbsp;&nbsp;&lt;datapoint>
&nbsp;&nbsp;&nbsp;&nbsp;&lt;id>2&lt;/id>
&nbsp;&nbsp;&nbsp;&nbsp;&lt;min>4.91142e-05&lt;/min>
&nbsp;&nbsp;&nbsp;&nbsp;&lt;avg>4.91142e-05&lt;/avg>
&nbsp;&nbsp;&nbsp;&nbsp;&lt;max>4.91142e-05&lt;/max>
&nbsp;&nbsp;&nbsp;&nbsp;&lt;t>2011-01-18 14:31:40&lt;/t>
&nbsp;&nbsp;&lt;/datapoint>
&nbsp;&nbsp;...
&lt;/latency>

I add the cloned &lt;latency> element to a new document like so:

&nbsp;&nbsp;&nbsp;&nbsp;var newEl = el.clone();
&nbsp;&nbsp;&nbsp;&nbsp;if (newEl) doc.root(newEl);

Here is the error Node.js (I'm on v0.6.8 and can't reasonably upgrade) sometimes tosses:

&nbsp;&nbsp;&nbsp;&nbsp;Assertion failed: (!handle_.IsWeak()), function Unref, file ../src/node_object_wrap.h, line 95.

The error is fatal to my worker process...it just dies.  I can't catch any exception.

The problem is with doc.root(newEl) when lots of nodes are involved.  The Node.js assertion error doesn't happen every time.  If I shorten the XML document to just a few rows of data, it seems to work reliably.  As the number of rows increases, so does the odds of receiving the assertion error, it seems.  With 10k rows, it happens 3 out of 4 times.

I've discovered that if I add a root node to the target document via node() and then do addChild() on the new root node, it seems to work reliably with the 10k rows.  So the problem looks to be specific to Document.root(el).

Will poke around the source code to see if I can spot the trouble.

**Comment by rchipka** [comment]
Pretty sure this is fixed by the memory management solutions @teleological and I worked on.
