### ISSUE TITLE
segmentation fault with libxmljs

### ISSUE THREAD

**Issue by SaltwaterC** [libxmljs/libxmljs#226]
I was checking for [XXE](https://www.owasp.org/index.php/XML_External_Entity_%28XXE%29_Processing), even though it shouldn't be possible with libxml2 2.9 used by OS X 10.9.2. Used node.js v0.10.26 and libxmljs v0.9.0.

The code used to trigger the segfault:

``` javascript
// xxe.js
var parser = require('libxml-to-js');
var xml = require('fs').readFileSync('./xxe.xml').toString()
parser(xml, function (err, res) {
    if (err) {
        console.error(err)
        process.exit(1)
    }
    console.log(res)
})
```

``` xml
<!-- xxe.xml -->
<?xml version="1.0" encoding="ISO-8859-1"?>
 <!DOCTYPE foo [
   <!ELEMENT foo ANY >
   <!ENTITY xxe SYSTEM "file:///etc/passwd" >]><foo>&xxe;</foo>
```

``` bash
node xxe.js
[1]    28749 segmentation fault  node xxe.js
```

[libxml-to-js](https://github.com/SaltwaterC/libxml-to-js) is just a wrapper for libxmljs that passes back a JavaScript object following the XML doc structure.

**Comment by teleological** [comment]
Fixed in #359

**Comment by rc0x03** [comment]
@teleological I think we can close this if you think it's been fixed by now. It's been more than a year and the memory management situation has evolved quite a bit in that time.

**Comment by teleological** [comment]
@rc0x03 The problem here is not due to memory management, but due to treating non-element nodes as elements,  and applying inapplicable operations to the wrapped nodes. I will clean up #359, which will address this issue.

**Comment by samskeller** [comment]
Is there any chance this can get fixed? I use `libxmljs` via the `libxml-to-js` package and the segmentation faults from this issue are causing us some problems. Thanks!
