### ISSUE TITLE
Not able to run libxmljs on node-webkit

### ISSUE THREAD

**Issue by piyushdevani** [libxmljs/libxmljs#237]
Hi,
When I use node on my x64bit Windows machine , I can use libxmljs properly,
but if I try to do the same thing in node-webkit console, I am getting this error.

%1 is not a valid Win32 application.
 D:\projrepo\nwtest\node_modules\libxmljs\build\Release\xmljs.node

Please help.
Thanks,
Piyush

**Comment by watheuer** [comment]
I was able to get it running using nw-gyp:
https://github.com/nwjs/nw.js/wiki/build-native-modules-with-nw-gyp

```
$ cd node_modules/libxmljs
$ npm install -g nw-gyp
$ nw-gyp configure --target=0.12.2
$ nw-gyp build
```
