### ISSUE TITLE
Error: Could not locate the bindings file.

### ISSUE THREAD

**Issue by NathanRSmith** [libxmljs/libxmljs#253]
Hi, I tried installing libxmljs on a CentOS6.5 server and received the following error:

```
/opt/node-server-qa/node_modules/libxmljs/node_modules/bindings/bindings.js:91
  throw err
        ^
Error: Could not locate the bindings file. Tried:
 → /opt/node-server-qa/node_modules/libxmljs/build/xmljs.node
 → /opt/node-server-qa/node_modules/libxmljs/build/Debug/xmljs.node
 → /opt/node-server-qa/node_modules/libxmljs/build/Release/xmljs.node
 → /opt/node-server-qa/node_modules/libxmljs/out/Debug/xmljs.node
 → /opt/node-server-qa/node_modules/libxmljs/Debug/xmljs.node
 → /opt/node-server-qa/node_modules/libxmljs/out/Release/xmljs.node
 → /opt/node-server-qa/node_modules/libxmljs/Release/xmljs.node
 → /opt/node-server-qa/node_modules/libxmljs/build/default/xmljs.node
 → /opt/node-server-qa/node_modules/libxmljs/compiled/0.10.29/linux/x64/xmljs.node
    at bindings (/opt/node-server-qa/node_modules/libxmljs/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/opt/node-server-qa/node_modules/libxmljs/lib/bindings.js:1:99)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/opt/node-server-qa/node_modules/libxmljs/index.js:4:16)
    at Module._compile (module.js:456:26)
```

Everything seemed to build ok, and I tried rebuilding several times.  (Sorry for the long paste):

```
$ node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@0.10.6
gyp info using node@0.10.29 | linux | x64
gyp info spawn python
gyp info spawn args [ '/usr/bin/gyp',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/opt/node-server-qa/node_modules/libxmljs/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/lib/node_modules/node-gyp/addon-rpm.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/share/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/usr/share/node',
gyp info spawn args   '-Dmodule_root_dir=/opt/node-server-qa/node_modules/libxmljs',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory `/opt/node-server-qa/node_modules/libxmljs/build'
  CC(target) Release/obj.target/libxml/vendor/libxml/buf.o
  CC(target) Release/obj.target/libxml/vendor/libxml/catalog.o
  CC(target) Release/obj.target/libxml/vendor/libxml/chvalid.o
  CC(target) Release/obj.target/libxml/vendor/libxml/dict.o
  CC(target) Release/obj.target/libxml/vendor/libxml/encoding.o
  CC(target) Release/obj.target/libxml/vendor/libxml/entities.o
  CC(target) Release/obj.target/libxml/vendor/libxml/error.o
  CC(target) Release/obj.target/libxml/vendor/libxml/globals.o
  CC(target) Release/obj.target/libxml/vendor/libxml/hash.o
  CC(target) Release/obj.target/libxml/vendor/libxml/HTMLparser.o
  CC(target) Release/obj.target/libxml/vendor/libxml/HTMLtree.o
  CC(target) Release/obj.target/libxml/vendor/libxml/legacy.o
  CC(target) Release/obj.target/libxml/vendor/libxml/list.o
  CC(target) Release/obj.target/libxml/vendor/libxml/parser.o
../vendor/libxml/parser.c: In function ‘xmlParseInNodeContext’:
../vendor/libxml/parser.c:13492: warning: pointer targets in passing argument 1 of ‘xmlFindCharEncodingHandler’ differ in signedness
../vendor/libxml/include/libxml/encoding.h:175: note: expected ‘const char *’ but argument is of type ‘const xmlChar *’
  CC(target) Release/obj.target/libxml/vendor/libxml/parserInternals.o
  CC(target) Release/obj.target/libxml/vendor/libxml/pattern.o
  CC(target) Release/obj.target/libxml/vendor/libxml/relaxng.o
  CC(target) Release/obj.target/libxml/vendor/libxml/SAX2.o
  CC(target) Release/obj.target/libxml/vendor/libxml/SAX.o
  CC(target) Release/obj.target/libxml/vendor/libxml/tree.o
  CC(target) Release/obj.target/libxml/vendor/libxml/threads.o
  CC(target) Release/obj.target/libxml/vendor/libxml/uri.o
  CC(target) Release/obj.target/libxml/vendor/libxml/valid.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xinclude.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xlink.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xmlIO.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xmlmemory.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xmlmodule.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xmlreader.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xmlregexp.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xmlsave.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xmlschemas.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xmlschemastypes.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xmlstring.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xmlunicode.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xmlwriter.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xpath.o
../vendor/libxml/trionan.c:218: warning: ‘trio_is_negative’ defined but not used
  CC(target) Release/obj.target/libxml/vendor/libxml/xpointer.o
  AR(target) Release/obj.target/vendor/libxml/xml.a
  CXX(target) Release/obj.target/xmljs/src/libxmljs.o
  CXX(target) Release/obj.target/xmljs/src/xml_attribute.o
  CXX(target) Release/obj.target/xmljs/src/xml_document.o
  CXX(target) Release/obj.target/xmljs/src/xml_element.o
  CXX(target) Release/obj.target/xmljs/src/xml_comment.o
  CXX(target) Release/obj.target/xmljs/src/xml_namespace.o
  CXX(target) Release/obj.target/xmljs/src/xml_node.o
  CXX(target) Release/obj.target/xmljs/src/xml_sax_parser.o
  CXX(target) Release/obj.target/xmljs/src/xml_syntax_error.o
  CXX(target) Release/obj.target/xmljs/src/xml_xpath_context.o
  SOLINK(target) Release/obj.target/xmljs.node
  SOLINK(target) Release/obj.target/xmljs.node: Finished
  COPY Release/lib.target/xmljs.node
make: Leaving directory `/opt/node-server-qa/node_modules/libxmljs/build'
gyp info ok
```

So I investigated and tried copying `cp build/Release/lib.target/xmljs.node build/xmljs.node` from within `node_modules/libxmljs/` and things started working.  Not sure what the issue is with the bindings file not being copied to the proper location, but thought someone should know.  Thanks.

**Comment by trestletech** [comment]
This is the only solution I could get working: https://github.com/gwicke/libxmljs/commit/7e1ceaf96021926871e07a397d53de63c136a22b

**Comment by sseide** [comment]
Hi,

When will the fix be available within the official version?
trying an "npm install libxmljs" with current version 0.14.2 gives the error from the initial report.
os: debian 8.1

thanks,
Stefan

**Comment by zwily** [comment]
I can't use the npm distributed version of libxmljs either because of this. gwicke@7e1ceaf also fixes it for me.

**Comment by ecbftw** [comment]
Still can't use libxmljs from npm.  Same problem.  I had to do this to work around it:

>  npm install libxmljs
>  (edit node_modules/libxmljs/binding.gyp to remove the 2 offending lines mentioned above)
>  cd node_modules/libxmljs/
>  node-gyp rebuild

I'm on Debian Sid (unstable).

**Comment by phil-oolabs** [comment]
I had this problem with the deasync and Node 5.6.0. Solved it with `node-gyp rebuild` also.

**Comment by gwicke** [comment]
FWIW, this is still happening for me:

- Node 4.4
- Debian sid
- gwicke@7e1ceaf still fixes it.

**Comment by rchipka** [comment]
Is anyone still affected by this issue?

**Comment by liambrownweb** [comment]
I'm running into it now. Tried on Windows, current versions of Node, NPM, and libxmljs.

**Comment by kuroware** [comment]
Ran into this issue today as well. Thanks for the above context and solutions everyone! <a href="https://github.com/gwicke/libxmljs/commit/7e1ceaf">gwicke@7e1ceaf</a> fixed this for me. 

<ul><li>`node -v`: v.7.6.0</li><li>`npm -v` 4.1.2</li><li>CentOS 6.5</li></ul>

**Comment by pedzed** [comment]
I am facing this issue as well. My OS is based on Ubuntu (which is based on Debian)

```bash
$ lsb_release -a
```
>No LSB modules are available.
Distributor ID:	elementary
Description:	elementary OS 0.4 Loki
Release:	0.4
Codename:	loki

**Comment by rainabba** [comment]
Myself as well now running in WSL (Ubuntu on Windows 10).

I've also tried `git clone`ing the source to node_modules and that got me no further.

To borrow from pedzed's wonderful format......

```
lsb_release -a
```
> No LSB modules are available.
> Distributor ID: Ubuntu
> Description:    Ubuntu 16.04.2 LTS
> Release:        16.04
> Codename:       xenial

```
node --version && npm --version
```
> v6.10.3
> 5.0.3

```
rm node_modules/ && yarn
```


```
npm install || npm rebuild --update-binary
```

> g++: error: /mnt/c/prj/AZPREP/GIT/WEB/BatchManWeb/node_modules/libxmljs-mt/build/Release/xmljs.node: No such file or directory
> node-libxslt.target.mk:140: recipe for target 'Release/obj.target/node-libxslt.node' failed
> make: *** [Release/obj.target/node-libxslt.node] Error 1
> make: Leaving directory '/mnt/c/prj/AZPREP/GIT/WEB/BatchManWeb/node_modules/libxslt/build'
> gyp ERR! build error
> gyp ERR! stack Error: `make` failed with exit code: 2
> gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
> gyp ERR! stack     at emitTwo (events.js:106:13)
> gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
> gyp ERR! System Linux 4.4.0-43-Microsoft
> gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
> gyp ERR! cwd /mnt/c/prj/AZPREP/GIT/WEB/BatchManWeb/node_modules/libxslt
> gyp ERR! node -v v6.10.3
> gyp ERR! node-gyp -v v3.6.2
> gyp ERR! not ok
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! libxslt@0.6.5 install: `node-gyp rebuild`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the libxslt@0.6.5 install script.

**Comment by morrisalp** [comment]
I also had this issue when building my project with libxmljs 0.18.4 and I had to use 0.18.3 instead. The node-gyp suggestion above did not solve this issue for me. Node v6.10.2, npm 3.10.10.

**Comment by masselit** [comment]
I had same problem
just try that:
projectToto > $ `sudo rm -rf  node_modules/`
projectToto > $ `npm install bindings`

**Comment by shmuel-web** [comment]
this on worked for me
projectToto > $ sudo rm -rf node_modules/
projectToto > $ npm install bindings
thanks @masselit

**Comment by MeiKatz** [comment]
Well, I tried the solutions above but none did work for me. So I solved it my way like this:
I changed `node_modules/libxmls/lib/bindings.js` from
```javascript
module.exports = require('bindings')('xmljs');
```
to
```javascript
module.exports = require('bindings')({
  "bindings": "xmljs",
  "module_root": "[path-to-my-project-folder]/node_modules/libxmljs",
});
```
Okay, it's not a bulletproof solution but it works for me. If anybody knows how to make this cleaner I want to hear it.

**Comment by cryptonkid** [comment]
After once you have done step as done by @MeiKatz  go back to the root project folder i.e. 
Drive:/<project-folder>/
and then run the rebuild command
`npm rebuild`

**Comment by All3xJ** [comment]
What I did was copying `cp build/Release/lib.target/xmljs.node build/xmljs.node` from within `node_modules/libxmljs/ `and things started working

as suggested by OP, and now it finally works.................. I wasted an afternoon.
