### ISSUE TITLE
implement skipXMLDeclaration and skipDTD during serialization

### ISSUE THREAD

**Issue by deepsweet** [libxmljs/libxmljs#258]
hi.

is it possible to implement a subject, like [XML::LibXML::Parser](http://search.cpan.org/dist/XML-LibXML/lib/XML/LibXML/Parser.pod#SERIALIZATION)? I want to try libxmljs with [svgo](https://github.com/svg/svgo), so I need more low-level control.

**Comment by matt-cook** [comment]
Same need here. It's pretty straightforward, I'd like to optionally omit `<?xml version="1.0" encoding="UTF-8"?>` when building a new document via `new libxmljs.Document()`. That is, I'd essentially like to build an XML fragment. This could be as simple as allowing `setDtd()` to accept empty values.
