### ISSUE TITLE
Parsing documents with encoding other than utf-8

### ISSUE THREAD

**Issue by arikon** [libxmljs/libxmljs#29]
There are problems parsing XML documents in encoding, other than utf-8, for example in windows-1251.
Comparing with python binding: parser opens document, recognizes encoding and returns all strings from document as unicode objects, properly converted from document encoding. When I need to modify document, I set new strings as unicode objects also, and during serialization to XML string they converted to the right encoding with respect to encoding property of the document.
This (or something similar) doesn't happen when working with such documents from node.js.

**Comment by joweste** [comment]
Hi, i have a xsd using "windows-1252" and I get the same problem.
