### ISSUE TITLE
Async use of NanAdjustExternalMemory causes crash with Node 0.12.1

### ISSUE THREAD

**Issue by gagern** [libxmljs/libxmljs#296]
I'm using node 0.12.1 and am investigating a segmentation fault in node-libxslt which builds on libxmljs. See albanm/node-libxslt#9.

I found that the segmentation fault occurs in a worker thread (i.e. not the V8 event dispatcher thread) when that thread runs some libxml code, and as a consequence calls `NanAdjustExternalMemory` at some point. In that thread, `v8::Isolate::GetCurrent()` will return `NULL`, causing the crash. The way I understand it, calls to V8 API from threads other than the event dispatcher thread are forbidden, including that Nan call.

Unfortunately I still have to find a good documentation on that `AdjustAmountOfExternalAllocatedMemory` method of the isolate, to see what repercussions we'd have to expect if we simply stopped telling V8 about our memory usage. But I guess 393b44a0010da5a469222291e9cad6be74f33a4c introduced that code for a reason. That commit is titled “first round of fixes for external memory issues” but doesn't say what kinds of issues these are. @polotek, do you remember any details?

If there is a really strong reason to keep these functions, then we'll probably have to work out how to make them function in an asynchroneous world. Implement some libuv signalling which reports adjustments from worker threads back to the event dispatch thread to be fed to V8. I very much hope that we don't really need this, since it might add considerable synchronization overhead.

**Comment by gagern** [comment]
I just realize that contrary to my assumption, libxmljs itself appears not to be designed for asynchroneous use cases. Would you nevertheless be willing to provide one configuration which is async-safe? Otherwise I fear node-libxslt would either have to fork this project, look for some other libxml wrapper or build one from scratch. I like none of these ideas. And I think that libxmljs might even profit from providing asynchroneous functions itself, either now or at some point in the future.

**Comment by albanm** [comment]
Just a small information extra. The problem is here: [https://github.com/polotek/libxmljs/blob/master/src/libxmljs.cc#L35](https://github.com/polotek/libxmljs/blob/master/src/libxmljs.cc#L35).

Some memory management wrapper around libxml. Which explains that this code was called implicitly when using a libxslt function that has no apparent connection with any libxmljs code.

**Comment by polotek** [comment]
@gagern I can tell you up front that we shouldn't remove the memory hints in libxmljs. The short explanation is that some of the data for xml docs is kept in v8 heap memory. v8 has some internal heuristics for when it decides to run garbage collection. The only thing you can do is give it hints to tell it how much memory you're using. If you don't send these hints, then v8 tends to wait a long time before deciding to do garbage collection. This is by design. But when people see the behavior, they usually interpret it as memory leaks. Giving these hints when heap memory changes results in more consistent gc and memory stays reasonable.

It sounds like the primary issue is that libxmljs is not designed to be entirely thread safe. I believe this is true of libxml2 as well, but don't quote me. I'm open to any changes that will help enable threaded usage. But I'm not sure @defunctzombie or I will be able to put a lot of time into that. If someone wants to work on this, we will take pull requests, and maybe even give commit access.

**Comment by polotek** [comment]
Let me explain this function in a little more detail. https://github.com/polotek/libxmljs/blob/master/src/libxmljs.cc#L23

When you're creating xml documents or fragments, libxml2 is allocating memory for them. Because it's embedded in a v8 binding, v8 wants to keep track of that memory to decide when to do garbage collection. The way libxml2 gives you to do this is a function that wraps the memory allocation so you can react in any way you need to. That's the function above. What we do is whenever memory gets allocated by libxml2, we give v8 a hint on how much memory we think we're using.

What this is means is that if you're using libxmljs, you may need to be able to get a v8 context at any time. I'm not familiar enough with how the worker context stuff is happening in node-libxslt to say if we can get around this requirement. @albanm maybe if you can give some more info on how you're managing situations like the above, we can start to adapt a similar solution for libxmljs.

**Comment by gagern** [comment]
Regarding the thread safety of libxml2, I found [this document](http://xmlsoft.org/threads.html). Apparently it is thread-safe, if it is compiled with the proper setting and if one does some manual locking. I'll have to look at the rest after I've had some sleep…

**Comment by polotek** [comment]
I was hoping to avoid mutexes and locks :-/

I should tell everyone that I'd like somebody who's much more confident
about that sort of thing than I am to review and weigh in here. If you are
that person or you know someone who'd be interested in helping out, let me
know.

**Comment by defunctzombie** [comment]
A quick look on the linked patch seems that it is correct.

Any perf implications we should care about here? I am assuming `NAUV_WORK_CB` will be called with every worker callback?

**Comment by gagern** [comment]
My experience is that an undestroyed `uv_async_t` will prevent the main loop from exiting when there is no more work to do. Afer all, there might be some code somewhere triggering that async and creating new work from this.

How about this alternate approach: we keep track of memory per thread, in [thread-local storage](http://docs.libuv.org/en/v1.x/threading.html#thread-local-storage). In the main thread, we delegate to `NanAdjustExternalMemory`. In the workers, we simply keep track of the changes, and it's the task of whoever starts a worker to feed the final difference back into V8. That avoids locks and their overhead. And since all the memory used in the worker thread cannot be freed by V8 doing a GC, it doesn't matter at that time.

**Comment by gagern** [comment]
Using `xmlMemUsed` would be impossible in a system with per-thread memory statistics, since it isn't per-thread. For `malloc` we could use the `size` argument as an indication of how much memory to allocate, but not for the others. Of course, we could allocate a bit more, and keep the size of the allocated block stored in there. None of this feels particularly elegant…

**Comment by gagern** [comment]
Using `xmlMemUsed` would be impossible in a system with per-thread memory statistics, since it isn't per-thread. But the more I think about it, the more I feel like we should simply duplicate the xml memory management functions and adjust them to our needs, instead of just wrapping them. After all, I just found out that `xmlMemUsed` [is not thread-safe](https://bugzilla.gnome.org/show_bug.cgi?id=747437) and also [may well overflow](https://bugzilla.gnome.org/show_bug.cgi?id=675412).

**Comment by gagern** [comment]
I'll write my own set of mem functions if noone beats me to it, but perhaps not within the next week.

**Comment by gagern** [comment]
I've written [my own memory management with TLS adjustment tracking](https://github.com/polotek/libxmljs/compare/master...gagern:threadLocalMemAdjust). I'll test to see whether this works in node-libxslt as intended, then file a pull request.

**Comment by gagern** [comment]
OK, everything works nicely. I've added some more code to ensure people actually use the new machinery. The whole thing is in #300 so please have a look at that and leave some comments what you think of this approach. It would be nice if we could get this included in the next release, so that node-libxslt can build on it.

**Comment by nathan7** [comment]
So, I've done some experiments, and this has nothing to do with thread-safety. libxmljs runs on the main thread as far as I can tell. If anyone wants to refute this, my results are at https://github.com/polotek/libxmljs/pull/299#issuecomment-90676810.

**Comment by nathan7** [comment]
Ah, it seems this *does* manifest when using albanm/node-libxslt. Bingo!

**Comment by nathan7** [comment]
@gagern While I think tracking this per-thread is interesting, I'm not convinced such a complex 200-line fix is worth it, without proof that the mutex is actually contended enough for it to make a difference.
My simpler fix, focused around a single mutex, is about 20 lines, and gets us the same results.
I'd like to see evidence that mutex contention is an actual performance issue.

**Comment by nathan7** [comment]
Furthermore, I'd like to see if we can avoid the (minor) performance cost of using the mutex in libxmljs's synchronous interface, the one we actually expose to JS. But for now, this fixes node-libxslt at a performance cost that I believe to be negligible.

**Comment by gagern** [comment]
@nathan7: I'd not be surprised if there actualy were some performance gain, since we drop the memory debugging data structures. But my main concern is that `xmlMemUsed` is not thread safe. So in my opinion we *have* to drop the wrappers around debug mem functions, and provide our own.

Combine that with the problem of cleanly closing the async. In fact my changes started with what I intended as one commit upon your code. In that I wrote the `isAsync` and `numWorkers` logic you still see in my code, with the intention of closing the async once the last worker was done. At that point I got concerned about some code launching the next worker before the close (which is an asynchroneous operation) got completed, and I didn't know how to handle that.

My point is, if we got your approach to a point where it would be operating cleanly, it would not be that smaller than my code. With all the locks and callbacks it might even be a bigger change. Discounting my `features` object, which amounts to many of these lines without adding much complexity. Also discounting `uvcompat.h` which is just a temporary burden while we support Node < 0.12, So unless there is some reason against TLS over async sends besides the footprint of the patch, I'd stick with my approach.

**Comment by nathan7** [comment]
Okay, if you're right and `xmlMemUsed()` is indeed not thread-safe, that makes my patch provisional at best. It does solve the immediate issue, and we're definitely reducing the amount of problems we have.
I'll have to spend some time with your code to figure out the rest.

**Comment by nathan7** [comment]
It might be possible to simply wrap all allocation/deallocation inside the mutex, making it thread-safe entirely at some performance cost in allocation. This would solve everything, save for performance issues. That gives us some time to investigate your approach, which I definitely would like to see integrated.

**Comment by nathan7** [comment]
I'd someone's opinion on https://github.com/nathan7/libxmljs/commit/bd2d065f09f0ae423eea26a9414b6ca76d463f1b, especially with regards to code style, because I have a somewhat idiosyncratic C/C++ style, and I'm not that well-informed on C++ conventions.
It's an approach more similar to #299, and similarly simple, but using @gagern's approach to tracking libxml's memory usage. It clocks in at ~40 lines of fairly easily understood code, and while I'm not code-golfing here, I'd like to keep complexity to a minimum.

**Comment by nathan7** [comment]
@defunctzombie
> Any perf implications we should care about here? I am assuming NAUV_WORK_CB will be called with every worker callback?

Nope, if there's already a pending callback, they will be coalesced, so we don't build up a giant pile of pending callbacks. We could even make sure we don't call into libuv at all if we know we already have a callback pending.

**Comment by gagern** [comment]
When choosing between #300 and #302, we might also want to keep in mind the following: up until now, libxmljs was inherently not thread-safe, and if some library like node-libxslt decides to use it in a multi-threaded environment, that's its own fault. Now you are becoming thread-safe, which is a very good thing. If you do so along the lines of #302, libraries won't even have to change their code. But a downside of this is that later on introducing a different approach which requires cooperation will become more difficult. So if you do #302 now and plan on doing #300 later, that would constitute a backwards-incompatible change. It will fail loudly at runtime, so it's not too bad, but still.

**Comment by gagern** [comment]
As far as I can tell, both #300 and #302 are ready for review and inclusion, and either one would get the job done. #302 requires less cooperation from libraries building on this, but appears to come with a CPU time overhead at least when the main loop is idle.

I consider the amount of cooperation required by #300 acceptable and indeed useful for future changes. I think it's also packaged in such a way that standard C++ RAII will take care of everything with very few extra lines of code. But I'm hardly objective when judging my own APIs.

Nathan considers his code easier to understand, and while I'm not sure I agree, again I'm not objective in that respect. At the moment the patch footprint looks not very much different: +177 -62 for #300 and +155 -60 for #302. The latter contains some libuv compat code which might go away eventually, while the former adds a `libxml.features` object which isn't strictly required but might be useful.

@defunctzombie: can you make a choice between approaches based on this information, and then review the better suited candidate? Or perhaps review both, and then merge the approach where you prefer the source code? Or should we provide any other information to evaluate the relative merits of both approaches?

**Comment by defunctzombie** [comment]
K, Ill try to find some time and review soon.

**Comment by gagern** [comment]
Any progress here? #302 has some fundamental problems with [per-thread symbols](https://github.com/polotek/libxmljs/blob/63a4cf205a221f74471d47dc8f0e7dc7ad247bfc/vendor/libxml/include/libxml/globals.h#L116-164) once pthread support gets enabled. #300 as an alternative looks good to me, but needs to be reviewed. In the meantime, node-libxslt got tired of waiting and started using gagern@d44be6148f05351eb76aaa92fc8fab4be80b295c from #300.

Are there any new developments which might make #302 viable again? Are there any serious concerns about how #300 works, except for the fact that it requires cooperation from the library using it, which seems unavoidable to me? Is there a real chance of getting #300 or some suitable equivalent of that merged any time soon? Or should I start looking for a new name so that I can make the code from #300 available on npm and continue developing it as a fork?

**Comment by gagern** [comment]
Since the use of a github dependency causes [some problems](https://github.com/albanm/node-libxslt/issues/15#issuecomment-120247805) for [node-libxmljs](https://github.com/albanm/node-libxslt), I've just officially forked libxmljs as [libxmljs-mt](https://www.npmjs.com/package/libxmljs-mt). But I have no intention of maintaining that fork any longer than needed, so I still hope you'll accept a working solution here soon.

**Comment by Klortho** [comment]
Any progress on reviewing this issue and the associated PRs? I've just been evaluating this library for potential use in our project, and it was very confusing at first to sort out the differences between these two forks. It seems clear to me that @nathan7 and @gagern have done some amazing work, that would really improve the quality of this library. I understand people are busy, but it seems like a shame to let it languish for so long.

**Comment by rchipka** [comment]
@gagern I'd like to add multithreading to the main libxmljs repo. How would you suggest going about it at this point? Should we merge the code from your fork? Any important updates since this was last reviewed?

Also, I think the API would be cleaner if we determined whether it's asynchronous by detecting whether there's a callback argument. So instead of `fromXmlAsync`, you can just call `fromXml(data, [callback])`.

**Comment by gagern** [comment]
@rchipka I'd be glad to see my changes merged in. Personally I'd like to see *all* my changes merged in, but I'm not sure whether that would meet the approval of the rest of the main project developers. In particular my use of a submodule to refer to the libxml codebase was rejected in #297, but I merged gagern@37fce27249e1ccb0179a0dec29de4f27d20b8d11 in gagern@e14cb5d2a6a4a4f5b097da644112304518332905.

Looking at [the diff](https://github.com/polotek/libxmljs/compare/master...gagern:master), the changes currently appear to fall into one of these categories:

1. Documentation changes due to fork. Most won't make sense once things got merged.
1. Code to make the library safe to use in a multi-threaded environment. That's what this is all about.
1. The `fromXmlAsync` function to showcase the above. Feel free to change as you see fit.
1. Code to include libxml symbols in DLL on Windows. See #386 on this.
1. AppVeyor config and some other changes for building on Windows. See #387 on this.
1. Vendor submodule, and ways to exclude auxiliary vendor code from shipped npm module. See #297.
1. Some Travis config changes. I suggest keeping these.
1. My name added to the `contributors` list in `package.json`. I insist on this, despite https://github.com/polotek/libxmljs/pull/361#discussion_r44951920.

> How would you suggest going about it at this point? Should we merge the code from your fork?

Depends on how much of the above you want to include. If you are OK with most of my changes, then it would be easiest to merge my branch into a feature branch, then revert specific files like documentation and perhaps the `vendor` subdirectory to what the current master has. I.e. do a `git checkout polotek/master -- README.md` or similar.

If, on the other hand, you want to separate concerns and only pick stuff related to the threading issue, then I suggest you cherry-pick the relevant commits off my branch. It might be useful to diff the result of that cherry-pick against my branch to make sure that all the remaining differences fall into one of the other categories outlined above. Note that for other modules building on libxmljs (like node-libxslt), #386 is probably at least as important as threading support, so it may make sense to address both of these. If you need help identifying the relevant commits, I can try to find time for it.

> Any important updates since this was last reviewed?

According to the way #300 renders its conversation, gagern@52c5eba92920a4f1335d1295d7e2c641d9006825 was the last commit actually reviewed by @defunctzombie. There were some quite important changes after that, like gagern@0ebc0605ad46321506cb172ee8d7e01271109572.

> Also, I think the API would be cleaner if we determined whether it's asynchronous by detecting whether there's a callback argument. So instead of `fromXmlAsync`, you can just call `fromXml(data, [callback])`.

I have no strong feelings here either way. That method is just an example to me, to show how multi-threaded operations work without a depending module. Feel free to change and extend this any way you like.

**Comment by rchipka** [comment]
@defunctzombie Are you still opposed to having @gagern listed as a contributor in package.json? He's made many significant contributions to this library and if we merge his multi-threading code I think he should be recognized for it.

**Comment by defunctzombie** [comment]
@rchipka I leave this up to you. I have made my comments on the matter here (https://github.com/polotek/libxmljs/pull/361/files/946a7bedc603b46126f182f8ffe6cb20795d58e5#r58493067). If you want to maintain an updated list and decide who is added based on contribution, go for it! I never cared that much about keeping such a list but have no opposition to you doing so. I contributed not to have my name listed but to create a library to solve my use cases and hope others benefit from that but I can understand how others might care more about name recognition.

**Comment by gagern** [comment]
@rchipka: This here has been dormant for quite a while now. Are you still interested in getting multi-threading into the master eventually, and thus ending the need for a fork? If so, please let me know which of the named changes you'd like to see merged, and whether you want them in a single merge request or a bunch of cherry-picks. The former would be easier for me.
