### ISSUE TITLE
Unable to install library v0.17.1 on Windows

### ISSUE THREAD

**Issue by ducky427** [libxmljs/libxmljs#385]
Hello,
I am trying to install the library on Windows 8.1 with node.js v5.1.1 and Visual Studio 2013 installed. 

I am getting the following error while trying to install the library:

```
Creating library .....\node_modules\libxmljs\build\Release\xmljs.lib and object .....\node_modules\libxmljs\build\Release\xmljs.exp
libxml.lib(parser.obj) : error LNK2001: unresolved external symbol snprintf [.....\node_modules\libxmljs\build\xmljs.vcxproj]
.....\node_modules\libxmljs\build\Release\xmljs.node : fatal error LNK1120: 1 unresolved externals [.....\node_modules\libxmljs\build\xmljs.vcxproj]
```

I am able to install v0.16.1 without any issues. 

Any help would be appreciated.

Thanks!

**Comment by joemalski** [comment]
I have the same issue with the latest version v0.17.1. btw, how did you install v0.16.1 in windows?  when i install it i have this error:

C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Platform.targets(57,5): error MSB8020: The build tools for v120 (Platform Toolset = 'v120') cannot be found. To build using the v120 build tools, please install v120 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution". [C:\Users\Gatekeeper-3\Desktop\ionic projects\custregistration-ionic\node_modules\libxmljs\build\vendor\libxml\libxml.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 6.3.9600

Any help is very much appreciated, Thanks.

**Comment by ducky427** [comment]
@joemalski, I have no clue. Looks like an issue using Windows 10 from [this](https://stackoverflow.com/questions/31792663/visual-studio-2013-error-ms8020-build-tools-v140-cannot-be-found)

**Comment by joemalski** [comment]
I was able to install **libxmljs** with this **version v.0.16.1** (just like you have advised) but not v0.17.1.  This might help out somebody out there.

1.) Install python version 2.7 for windows then add this to your "User Variables PATH" 
    ** C:\Python27;C:\Python27\Scripts**

2.) Restart your PC.

3.) Install **Visual Studio 2013**

4.) After installing **Visual Studio 2013**, Add **GYP_MSVS_VERSION=2013** to your 
     user environment variables.
     i.e. right-click start -> system -> advanced system settings -> environment variables -> 
     "user variables for [username]" -> new
     Make sure you open a new console after doing this, so that the environment variable 
     addition is picked up.

5.) npm's 'python' config key to the appropriate value: 
     **npm config set python /path/to/executable/python2.7**

6.) Set the path of **Microsoft.Cpp.Default.props**:
     **set VCTargetsPath=C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120**

7.) then install libxmljs with **version 0.16.1**
     **npm install libxmljs@v.0.16.1**

I just "pieced" these links together by following the errors I have encountered:

https://github.com/apla/me.apla.cordova.app-preferences/blob/b55e7b0/README.md
https://github.com/nodejs/node-gyp/issues/679
https://github.com/nodejs/node-gyp
http://stackoverflow.com/questions/21069699/node-packages-not-building-on-windows-8-1-missing-microsoft-cpp-default-props

**Comment by ducky427** [comment]
good stuff @joemalski!

**Comment by Raptor399** [comment]
Is there a way to install libxmljs without being dependent on a compiler? Is there a binary release available?

It feels a bit strange to have to install Microsoft Visual Studio on Windows in order to be able to do "npm install libxmljs".

**Comment by joemalski** [comment]
I am not aware of any.  As of now, it is the way I do it and it works. I am sure there is a better way.

**Comment by ducky427** [comment]
@Raptor399, its certainly possible but it requires non-trivial operation changes. It can be acheived using [node-pre-gyp](https://www.npmjs.com/package/node-pre-gyp)

**Comment by Raptor399** [comment]
@joemalski Nothing wrong with your solution, it's good to know it exists and thank you for sharing it!

It's just that I'm not used to npm modules having dependencies to (possibly unavailable) external software packages. Npm modules always seemed pretty self-contained to me as a user, and I found it surprising to see C++ compilation with warnings popping up in the installation process on Mac OS X.

@ducky427 That sounds interesting, thanks for the pointer!

**Comment by sp00x** [comment]
Are you actually getting this to compile even with 0.16.1 in newer versions of Node, after 0.12.x ? E.g. current LTS 4.4 ?

I am getting a ton of errors indicating some kind of other-level wrong, bunch of V8 related errors, etc e.g.

C:\Users\rune\.node-gyp\4.4.5\include\node\v8.h(336): error C2988: unrecognizable template declaration/definition [C:\Temp\test\node_modules\libxmljs\build\xmljs.vcxproj]
C:\Users\rune\.node-gyp\4.4.5\include\node\v8.h(336): error C2059: syntax error : 'using' [C:\Temp\test\node_modules\libxmljs\build\xmljs.vcxproj]
etc

Using VS2012 developer command prompt.

**Comment by sp00x** [comment]
Update: 0.18.0 builds with Visual Studio 2015 Desktop edition installed, running from "Developer cmomand prompt" and with `set GYP_MSVS_VERSION=2015`

**Comment by Ivanca** [comment]
@sp00x  ...there is no Visual Studio edition called "Desktop edition", the only ones available are Community, Professional, Enterprise, Code (https://beta.visualstudio.com/downloads/)

**Comment by sp00x** [comment]
@Ivanca I guess I meant "Express". Now you can probably just use the build tools package instead ( https://www.npmjs.com/package/windows-build-tools instead )

**Comment by rchipka** [comment]
The `snprintf` issue has been fixed for a while now and it is definitely fixed in the precompiled binaries.
