### ISSUE TITLE
Support for newer version of node?

### ISSUE THREAD

**Issue by seanmcilvenna** [libxmljs/libxmljs#393]
Hi, I'm trying to determine if I can upgrade my project to a newer version of node.js...
I am actively using libxmljs with node 0.12.7 32bit.
I would like to upgrade my project to use node 4.2.1. Does libxmljs support node 4.2.1? I tried installing with node 4.2.1 and got a ton of errors, just not sure if they are related to the node version, or something else...

**Comment by rchipka** [comment]
I'm running libxmljs on node 4.2.1 without any issues. What errors are you getting?

**Comment by seanmcilvenna** [comment]
A ton... See attached.
[libxmljsbuild.txt](https://github.com/polotek/libxmljs/files/188682/libxmljsbuild.txt)

**Comment by seanmcilvenna** [comment]
Made a little progress... Found a thread that said node-gyp needs VS 2013 or 2015 to compile with C++ 11. So, I happen to have VS 2013 installed, and ran the developer tools for VS 2013.

After running "npm install libxmljs --msvs_version=2013", I get less errors, but still get errors. See attached.

[libxmljsbuild.txt](https://github.com/polotek/libxmljs/files/188712/libxmljsbuild.txt)

**Comment by seanmcilvenna** [comment]
Looks like others are having the same problem: https://github.com/polotek/libxmljs/issues/392

**Comment by codedogs** [comment]
@seanmcilvenna To confirm, does libxmljs work on an older nodejs for you?

**Comment by seanmcilvenna** [comment]
Yes, it works for me on 0.12.7

**Comment by seanmcilvenna** [comment]
Anyone have any ideas?

**Comment by seanmcilvenna** [comment]
It looks like there is a breaking change between version 0.16.1 and 0.17.1...
0.16.1 compiles fine, but 0.17.0 and 0.17.1 don't
