### ISSUE TITLE
a valid literal '>' in text gets encoded as &gt;

### ISSUE THREAD

**Issue by msklvsk** [libxmljs/libxmljs#399]
``` js
var libxmljs = require("libxmljs");

var doc = libxmljs.parseXml("<x> a>b </x>");
console.log(doc.toString());
// outputs '<x> a&gt;b </x>' while original '<x> a>b </x>' expected
```

**Comment by michael-ericson-tanium** [comment]
This is the behavior of libxml2, which is perfectly fine; the parser simply chooses to replace the character with its equivalent entity.

Note that when you get the text of that element you get the properly decoded character:

```js
var libxmljs = require('libxmljs');
var doc = libxmljs.parseXml('<x> a>b </x>');
doc.get('/x').text(); // => ' a>b '
```

**Comment by msklvsk** [comment]
Thank you. Today I have no idea why I even posted this back in April.
