### ISSUE TITLE
build\vendor\libxml\libxml.vcproj is not here?

### ISSUE THREAD

**Issue by circuitfry** [libxmljs/libxmljs#409]
Hi, I'm completely unaware of how Node.js works, I just want to run a thing without having to run a virtual machine. Do you know how I can get this file? It's not in this current source, how would I generate it, or does it have to come from the thing I'm trying to run?

**Comment by defunctzombie** [comment]
stackoverflow and google is your friend

**Comment by circuitfry** [comment]
That was extremely condescending and assumptive.
