### ISSUE TITLE
libxmljs/build/Release/xmljs.node: undefined symbol

### ISSUE THREAD

**Issue by ohadinho** [libxmljs/libxmljs#425]
OS: LINUX Mint

```
node -v
v4.4.7
npm -v
2.15.8
node-gyp -v
v3.4.0
```

libxmljs version is 0.18.0

I've install `libxmljs` inside a module i'm building.
I ran the app (which uses that module i'm building) and this weird error came up:

```
node_modules/libxmljs/build/Release/xmljs.node: undefined symbol: _ZN2v82V837AdjustAmountOfExternalAllocatedMemoryEl
    at Error (native)
    at Object.Module._extensions..node (module.js:434:18)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at bindings
```

**Comment by ohadinho** [comment]
Still stuck with this issue.

**Comment by rchipka** [comment]
Try building the latest version. Will reopen if the problem persists.

**Comment by gonzo09** [comment]
Hello,
I have same issue with v0.19.10. 

```node: symbol lookup error: /builds/qvKYzUwQ/2/serum/serum/node_modules/libxmljs/build/Release/xmljs.node: undefined symbol: _ZN2v87Isolate37AdjustAmountOfExternalAllocatedMemoryEl```

It executes on a Kubernetes executor with docker image node:14.19.3-bullseye.
I feel that I tried everything.
