### ISSUE TITLE
How to get the current element name?

### ISSUE THREAD

**Issue by tuananh** [libxmljs/libxmljs#427]
I was trying to get the element name using `name()` but somehow it returns `XPath error : Invalid expression`

My example xml is `<Fare Amount="990.00"/>` and i was trying to get it using `\\Fare\name()`

Does libxmljs support this?

**Comment by hildjj** [comment]
Do you have to use the xpath expression to get the name?

```javascript
const libxmljs = require('libxmljs')
const doc = libxmljs.parseXml('<Fare Amount="990.00"/>')
console.log(doc.get('/*').name())
```

output: `Fare`

**Comment by tuananh** [comment]
@hildjj thank you. it works.
