### ISSUE TITLE
list of attributes

### ISSUE THREAD

**Issue by carloscarvallo** [libxmljs/libxmljs#430]
Sorry for this, but I have read the documentation but this method it's not clear to me

``` javascript
var xml =  '<?xml version="1.0" encoding="UTF-8"?>' +
           '<root>' +
               '<child foo="bar" como="perro">' +
                   '<grandchild baz="fizbuzz">grandchild content</grandchild>' +
               '</child>' +
               '<sibling>with content!</sibling>' +
           '</root>';

var xmlDoc = libxml.parseXmlString(xml);;
var children = xmlDoc.root().childNodes();
var child = children[0];
var attributes = child.attrs();

for (key in attributes) {
  console.log(attributes[key]);
}

//output
//{}
//{}
```
why it is empty?

**Comment by hildjj** [comment]
`console.log(attributes[key].value())`

**Comment by carloscarvallo** [comment]
thnx @hildjj

**Comment by hildjj** [comment]
Say more about what you want, please?  `attributes` is an array of the attributes for the `child` attribute.  The docs for the Attribute class are here: https://github.com/libxmljs/libxmljs/wiki/Attribute

If you want the name, you call `.name()`.  If you want the namespace URI, you call `.namespace().href()`.

**Comment by carloscarvallo** [comment]
.name() is working for me... thnx @hildjj
