### ISSUE TITLE
//title and //title/text() are the same

### ISSUE THREAD

**Issue by Kidel** [libxmljs/libxmljs#436]
When I use //title I usually expect something like

```
<title>Something</title>
```

While applying  //title/text() should result in

```
Something
```

But in libxmljs //title and //title/text() are the same. Is there a way to fix this and obtain the normal node?

Thank you

**Comment by michael-ericson-tanium** [comment]
Those XPath queries actually return different [DOM `Node` types](https://developer.mozilla.org/en-US/docs/Web/API/Node):

- The object at xpath `/title` is an [`Element` node](https://developer.mozilla.org/en-US/docs/Web/API/Element).
- The object at xpath `/title/text()` is a [`Text` node](https://developer.mozilla.org/en-US/docs/Web/API/Text).  

Element nodes may have children, including other elements or text nodes, and the [`textContent` or `text()` method in libxmljs](https://developer.mozilla.org/en-US/docs/Web/API/Node/textContent) will return their contents. Consider the following example:

```js
var libxmljs = require('libxmljs');
var doc = libxmljs.parse('<title>Something</title>');

var titleElement = doc.get('/title');
titleElement.type(); // => 'element'
titleElement.name(); // => 'title'
titleElement.toString(); // => '<title>Something</title>'
titleElement.text(); // => 'Something'

var titleText = doc.get('/title/text()');
titleText.type(); // => 'text'
titleText.name(); // => 'text', DOM doesn't specify a name for text nodes but this is convenient.
titleText.toString(); // => 'Something'
titleText.text(); // => 'Something'
```

**Comment by rchipka** [comment]
@michael-ericson-tanium Your answer is spot on, although I will say that _technically_ they aren't DOM types. I wish they were. It'd make [libxmljs-dom](https://github.com/libxmljs/libxmljs-dom)'s job a bit easier.
