### ISSUE TITLE
Compilation fails when compiler requires flag to support C++11

### ISSUE THREAD

**Issue by KennethRogers** [libxmljs/libxmljs#437]
Using older (prior to v6.0 of gcc?) compilers the compilation is failing.
I think this is the important error message:
 `../../nan/nan.h:43:3: error: #error This version of node/NAN/v8 requires a C++11 compiler`

I think this might be fixed by adding -std=c++11 to the compiler options.

**Comment by rchipka** [comment]
Can you create a PR for this?

**Comment by rchipka** [comment]
Fixed in v0.18.7
