### ISSUE TITLE
Yet another `node-gyp rebuild` issue

### ISSUE THREAD

**Issue by phillipadsmith** [libxmljs/libxmljs#440]
Have read many posts on this mysterious `node-gyp rebuild` failure. Have tried all of the proposed solutions. Nothing has worked so far. Suggestions welcome:

```
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/phillipadsmith/.ndenv/versions/v4.2.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.8.6-x86_64-linode78
gyp ERR! command "/home/phillipadsmith/.ndenv/versions/v4.2.1/bin/node" "/home/phillipadsmith/.ndenv/versions/v4.2.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/phillipadsmith/canadian-headlines-scrapers/node_modules/osmosis/node_modules/libxmljs-dom/node_modules/libxmljs
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm ERR! Linux 4.8.6-x86_64-linode78
npm ERR! argv "/home/phillipadsmith/.ndenv/versions/v4.2.1/bin/node" "/home/phillipadsmith/.ndenv/versions/v4.2.1/bin/npm" "upgrade"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
```

npm 2.14.7
On Ubuntu 12.04 LTS. 

Have tried with newer versions of node/npm also. Same error.

**Comment by vdanielpop** [comment]
I have the same issue, 
npm 3.10.10 on Ubuntu 14.04 LTS

**Comment by graphicore** [comment]
I also ran into this, different versions of almost anything.

```js
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.0-53-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/commander/Projekte/atem/Atem-MOM/node_modules/libxmljs
gyp ERR! node -v v6.9.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm ERR! Linux 4.4.0-53-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.9.2
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE

npm ERR! libxmljs@0.16.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
```

**Comment by officeabg** [comment]
I confirm! Nothing works trying do make it work!

**Comment by hildjj** [comment]
Can you look a little further up in the error log, and see if you can find a C++ compiler error?

**Comment by phillipadsmith** [comment]
@hildjj Here's the full output of the install process:
https://gist.github.com/phillipadsmith/426b5231bdf53c21b99e7486147a6f0e

npm 2.14.7
On Ubuntu 12.04 LTS.

**Comment by hildjj** [comment]
Doesn't look like we're logging compiler version, but it looks like whatever C++ compiler you're using doesn't support C++11.

**Comment by graphicore** [comment]
@defunctzombie so what do you suggest should we do to solve our installation problems. I'm asking since you closed the issue.

**Comment by defunctzombie** [comment]
Without seeing your complete log file I cannot say (because the portion of the log you posted is not helpful). But you should make sure you have a modern(ish) compiler that can build c++11 and that you have met the dependencies described here: https://github.com/nodejs/node-gyp

**Comment by graphicore** [comment]
Ok, since this is a current xubuntu running here, we can safely assume that c++11 is supported by gcc. 

I just figured out that I can't build `libxmljs@0.16.1` but `libxmljs@0.18.0` builds fine. That suffices me. I updated the package.json that requires libxmljs.

**Comment by phillipadsmith** [comment]
> Doesn't look like we're logging compiler version, but it looks like whatever C++ compiler you're using doesn't support C++11.

Seems unlikely, but I'll double check.
