### ISSUE TITLE
Error 193 when requiring libxmljs

### ISSUE THREAD

**Issue by apazureck** [libxmljs/libxmljs#441]
Hi,

I have trouble using libxmljs with node.js.

I have installed the package via npm. When I am trying to do `var libxmljs = require('libxmljs');` I get the following error:

> Error: error: 193\\?\c:\Users\pazureck\nodelanguageserver\vscode-languageserver-node-example\client\server\node_modules\libxmljs\build\Release\xmljs.node
>     at Error (native)
>     at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:178:20)
>     at Object.Module._extensions..node (module.js:583:18)
>     at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:178:20)
>     at Module.load (module.js:473:32)
>     at tryModuleLoad (module.js:432:12)
>     at Function.Module._load (module.js:424:3)
>     at Module.require (module.js:483:17)
>     at require (internal/module.js:20:19)
>     at bindings (c:\Users\pazureck\nodelanguageserver\vscode-languageserver-node-example\client\server\node_modules\bindings\bindings.js:76:44)

I use:
- Windows 10
- node v6.9.1
- libxmljs 0.18.0

Did I do something wrong? Installation just went through fine.

**Comment by rchipka** [comment]
That stack trace doesn't give much information. My guess is that you're running the script using a different version of node than the version that libxmljs was compiled with.

**Comment by rchipka** [comment]
Builds are working on AppVeyor. Try building latest version or a try precompiled binary.

Will reopen if problem persists.
