### ISSUE TITLE
install fails on windows

### ISSUE THREAD

**Issue by ainthek** [libxmljs/libxmljs#442]
$ node --version
v6.9.1

$ npm --version
4.0.2

running from Git2.0 bash console and from standard cmd, both fails....

$ npm install libxml

> libxml@0.0.7 preinstall C:\workspaces\....\node_modules\.staging\libxml-e08c8558
> ./build.sh

'.' is not recognized as an internal or external command,
operable program or batch file.
npm WARN iclose@1.0.0 No description
npm WARN iclose@1.0.0 No repository field.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\meebo\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "libxml"
npm ERR! node v6.9.1
npm ERR! npm  v4.0.2
npm ERR! code ELIFECYCLE

npm ERR! libxml@0.0.7 preinstall: `./build.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the libxml@0.0.7 preinstall script './build.sh'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the libxml package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./build.sh
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs libxml
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls libxml
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\workspaces\upm2-igate\iclose\npm-debug.log

**Comment by defunctzombie** [comment]
See all the other issues about this for help.

**Comment by ainthek** [comment]
Sorry i have probably reported to wrong project :-)
