### ISSUE TITLE
deprecated apis - compilation fails in node version 6.9.3

### ISSUE THREAD

**Issue by PSeitz** [libxmljs/libxmljs#455]
The compilation in node 6.9.3 fails because some deprecated apis are used , eg:

../src/libxmljs.cc:60:17: error: 'IsDead' is deprecated [-Werror,-Wdeprecated-declarations]
    if (v8::V8::IsDead())
                ^
/Users/user1/.node-gyp/6.9.3/include/node/v8.h:8666:10: note: 'IsDead' has been explicitly marked deprecated here
bool V8::IsDead()

**Comment by rchipka** [comment]
This is fixed in the latest version. Just waiting on someone to publish to NPM.

@defunctzombie Would you consider `npm owner add rchipka`?

**Comment by defunctzombie** [comment]
> @defunctzombie Would you consider npm owner add rchipka?

Done

**Comment by rchipka** [comment]
@defunctzombie Thanks!

Published v0.18.4
