### ISSUE TITLE
Use platform-specific build path

### ISSUE THREAD

**Issue by bwknight877** [libxmljs/libxmljs#458]
**Problem**: the native node module `xmljs.node` does not go into a uniquely named directory.

It only gets compiled to `./build/Release/xmljs.node`

**Why I care**: this is a problem because we would like to create a node distribution that will work and install across multiple platforms (windows and linux)

If we merge two `node_modules` directories from windows and linux, then xmljs.node gets overwritten with either a windows or linux binary.

Other npm packages like sqlite3 do not have this problem because their native node module goes into `./lib/binding/{node_abi}-{platform}-{arch}`

The documentation for [node-pre-gyp](https://github.com/mapbox/node-pre-gyp) shows how to make this work.

I'll submit a PR for this issue as I've already forked and fixed it.

**Comment by rchipka** [comment]
Looking into that PR now. It should be good to merge as long as it doesn't affect the prebuilt Windows binary deployment.

Also, if you'd like libxmljs to support prebuilt binaries for linux and macOS (via travis), I'd gladly accept a PR for that as well ;)
