### ISSUE TITLE
`No rule to make target` when root tries to install libxmljs with npm

### ISSUE THREAD

**Issue by pedro-nonfree** [libxmljs/libxmljs#465]
I came here to report a bug related to installation of `genieacs` that uses `libxmljs`

so by default npm don't want to use root directory (`user "root" does not have permission to access the dev dir`), and this temporary directory is not fine for libxmljs so gives `No rule to make target`

to solve it, I forced installation as root like this:
`npm install genieacs --unsafe-perm -g`

I just wanted to report this because, I spent 30 minutes to figuring out what's happening. Save your 30 min.

the error in a nutshell:

```
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/7.9.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/libxmljs/.node-gyp"
gyp http GET https://nodejs.org/download/release/v7.9.0/node-v7.9.0-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v7.9.0/node-v7.9.0-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v7.9.0/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v7.9.0/SHASUMS256.txt
make: Entering directory '/usr/lib/node_modules/libxmljs/build'
make: *** No rule to make target '../.node-gyp/7.9.0/include/node/common.gypi', needed by 'Makefile'.  Stop.
```

**Comment by rchipka** [comment]
Looks like a permissions problem. Probably fixed by the latest pre-compiled binary support anyways.
