### ISSUE TITLE
Parsing SVG text converts all attributes to lower-case

### ISSUE THREAD

**Issue by stsvilik** [libxmljs/libxmljs#468]
When parsing, then manipulating SVG content, toString output seems to convert all attributes to lower case thus rendering SVG useless. There at least should be an option either in toString formatter or parser to preserve attribute case (camel-case).

**Comment by stsvilik** [comment]
Is this issue scheduled to be addressed?

**Comment by HungryOrc** [comment]
Hopefully this issue can be resolved

**Comment by rchipka** [comment]
Are you using parseHtml or parseXml?

You could also try this:

```javascript
document.toString({
  type: 'xml'
});
```

**Comment by HungryOrc** [comment]
> Are you using parseHtml or parseXml?You could also try this:

Thanks a lot! I was using "parseHtmlString". After I shifted to "parseXmlString", all the lower/upper cases of the elements were kept intact. Wonderful!

**Comment by rchipka** [comment]
I'm closing this issue. I will reopen it if this issue can be reproduced while using parseXmlString.

**Comment by stsvilik** [comment]
This is not a 100% solution - since SVG may be embedded in HTML (pretty common) in which case serializing it as XML will potentially damage HTML content.

**Comment by rchipka** [comment]
Have you tested serializing an SVG embedded in HTML? If libxml does not properly handle that, then it's an issue with libxml.
