### ISSUE TITLE
Precompiled binaries for Electron via pre-gyp

### ISSUE THREAD

**Issue by WolfieMario** [libxmljs/libxmljs#488]
I would like to develop Atom packages which use libxmljs. However, Atom requires native binaries to be compiled for the Electron version it runs on (or at least any ABI-compatible version of Electron, I think).

libxmljs provides pre-built binaries for several Node versions, but no versions of Electron.
pre-gyp does support Electron, and `apm install` attempts to download the appropriate binary (where the name starts with "electron-" instead of "node-"). This will fail for libxmljs because no compatible prebuilt binary exists, and it will fall back to compiling from source:

    node-pre-gyp http GET https://github.com/libxmljs/libxmljs/releases/download/v0.18.7/electron-v1.6-win32-x64.tar.gz
    node-pre-gyp http 404 https://github.com/libxmljs/libxmljs/releases/download/v0.18.7/electron-v1.6-win32-x64.tar.gz
    node-pre-gyp ERR! Tried to download(404): https://github.com/libxmljs/libxmljs/releases/download/v0.18.7/electron-v1.6-win32-x64.tar.gz
    node-pre-gyp ERR! Pre-built binaries not found for libxmljs@0.18.7 and electron@1.6.9 (electron-v1.6 ABI) (falling back to source compile with node-gyp)
    node-pre-gyp http 404 status code downloading tarball https://github.com/libxmljs/libxmljs/releases/download/v0.18.7/electron-v1.6-win32-x64.tar.gz

I would like to avoid requiring my package users to build libxmljs (more on why later). What is the recommended course of action here?
Can libxmljs provide pre-built binaries for recent versions of Electron? Would that introduce an undesirable maintenance burden?

If that isn't acceptable, can a Node package depending on libxmljs provide its own pre-built binaries? I'm still new to Node and not very familiar with how pre-gyp works, but it doesn't seem like this is possible without some hacks. From what I can tell, at installation time, libxmljs will automatically try downloading a pre-built binary and fall back to building the native module when that fails.
Is there any non-hacky way for a depending package to override this behavior, and have pre-gyp first try getting a precompiled binary from a different source (i.e., not https://github.com/libxmljs/libxmljs/releases/, which doesn't provide electron- binaries), and only fall back to the usual libxmljs installation route if that fails?

If neither of those options works (i.e., libxmljs *won't* provide Electron binaries, and a package depending on it *can't* provide them), should I just fork my own version of libxmljs, and have *that* provide Electron binaries? I'd really like to avoid unnecessarily forking the project if possible.

**Comment by WolfieMario** [comment]
A bit more on _why_ I would like precompiled native binaries for Electron:

Atom is a text editor built on top of Electron. It has a package manager, `apm`, which is similar to `npm` in many respects.
Atom packages are special Node packages which are installed by end-users to expand the editor's functionality. An Atom package may (and almost always will) depend on ordinary Node packages. Atom packages cannot depend on other Atom packages, because they are meant to be singletons within the Atom environment, installed by the user.
Most Atom users don't actually install packages on the command line with `apm install`. Atom provides a UI within the editor for finding and installing community-provided Atom packages.

If an Atom package has native module dependencies, it is supposed to provide pre-built binaries for all Atom/Electron versions the package intends to support. If an Electron update (resulting from updating Atom) breaks ABI compatibility and an installed package doesn't provide a pre-built binary compatible with the new version, a UI lets the user know:
https://atom.io/packages/incompatible-packages
This UI lets the user disable the package, recompile the native modules, or report a bug to the package author.

Unfortunately, the user experience for installing a _new_ Atom package with incompatible native module dependencies isn't so friendly (not that this situation was very friendly to begin with).
If the user meets the node-gyp build requirements, installation will take an unusually long time, because the native binary has to be recompiled at installation time. Sadly, the UI doesn't explain that's what's going on. Worse, of course, is if the build fails. The user just gets an unfriendly red error popup telling them to file a bug report against the Atom package.

Setting up a node-gyp compatible build environment also isn't exactly the most straightforward or quick thing to do, at least on Windows. And on top of the usual instructions, you have to realize that `npm config` settings won't propagate to `apm`, so you need to configure that separately. Not at all obvious if you just wanted to install an Atom package from the UI and don't even know what `apm` is.

Of course, this isn't really a problem with Atom's UX. End users simply shouldn't *need* to compile a package just to install it. There are many reasons building the native modules could fail, and none of them are things an end user (even of a text editor targeted at programmers) should have to worry about. A node-gyp compatible C/C++/Python build environment shouldn't be a requirement for using a text editor, after all.

Anyways, sorry about the rant. I do want to say that libxmljs is a great library; this is why I want to use it to create XML editing/authoring packages for Atom 😁
I was hoping having libxmljs directly provide Electron binaries would be feasible, since this would avoid hacks or forking, and would also allow other Atom and Electron platform authors use libxmljs with ease.

**Comment by rchipka** [comment]
@WolfieMario do you know if we can build for electron on Travis or AppVeyor?

Would it be sufficient to upload a renamed copy of each build asset so that it matches the request URL?

**Comment by s4m0r4m4** [comment]
Hello, I'm in a similar boat of wanting a version of libxmljs prebuilt for electron. I don't know for sure, but I do not think you can simply rename the existing builds made directly from node.

I'm out of my depth here, but it does seem like there are resources for building electron on AppVeyor and/or Travis using the electron-builder plugin:
- https://bretahajek.com/2016/11/electron-builder-appveyor-travis-ci-memory-king/
- https://gist.github.com/develar/bdf242a3cbf6120ed2300337f71e0982

I use electron-builder to build electron apps on my local machine and it works just fine, don't know how well that experience translates to AppVeyor or Travis.
