### ISSUE TITLE
Node doesn't gc document.root()

### ISSUE THREAD

**Issue by monkeysuffrage** [libxmljs/libxmljs#490]
I wonder if anyone would like to weigh in on this:
https://stackoverflow.com/questions/46840560/node-doesnt-gc-my-object-properly/46844796

```
let html = `<<some huge html file>>`
var libxmljs = require("libxmljs");

class MyObject{
  constructor(html){
    this.doc = libxmljs.parseHtml(html);
    this.node = this.doc.root()
  }
}

let obj

for(var i = 0; i < 100000; i++){
  obj = new MyObject(html)
  // if I uncomment the next line it works fine
  // obj.node = null
  console.log(i)
}

```
Huge memory leak when running this script. Is libxmljs at fault here, or is Node?

**Comment by faustman** [comment]
I guess you don't give a chance for a GC work.

You should process your HTML in the separate event loop tick, like:

```
//...
for(var i = 0; i < 100000; i++) {
  ((i) => {
    setImmediate(() => {
      // .. your code
    })
  })(i)
}
```

**Comment by rchipka** [comment]
@monkeysuffrage I believe we have a test for this and it's passing.

Take a look at the tests and try using the NodeJS memory debugging functions in your test code.

If the problem persists I'll re-open this issue.

**Comment by monkeysuffrage** [comment]
Thanks Robbie!
I'd like to check it out but I see there's no windows release so maybe I'll
try again in the future.

**Comment by monkeysuffrage** [comment]
I got a chance to try this today with version 0.18.9-pre0 + node v10.1.0 and unfortunately I see the same behavior :(
