### ISSUE TITLE
Install failed on CentOS6.3, node version 9.10.1

### ISSUE THREAD

**Issue by aiddroid** [libxmljs/libxmljs#503]
Install failed on CentOS6.3(x64), node version 9.10.1, npm 5.6.0

errors in /.npm/_logs/2018-04-02T13_17_05_494Z-debug.log

2475 silly saveTree ├─┬ stryker@0.20.1
2475 silly saveTree │ ├─┬ chalk@2.3.2
2475 silly saveTree │ │ ├── ansi-styles@3.2.1
2475 silly saveTree │ │ └── supports-color@5.3.0
2475 silly saveTree │ ├── commander@2.15.1
2475 silly saveTree │ ├─┬ log4js@1.1.1
2475 silly saveTree │ │ └─┬ streamroller@0.4.1
2475 silly saveTree │ │   ├── date-format@0.0.0
2475 silly saveTree │ │   ├── debug@0.7.4
2475 silly saveTree │ │   └─┬ readable-stream@1.1.14
2475 silly saveTree │ │     ├── isarray@0.0.1
2475 silly saveTree │ │     └── string_decoder@0.10.31
2475 silly saveTree │ ├── prettier@1.11.1
2475 silly saveTree │ ├── progress@2.0.0
2475 silly saveTree │ ├── rimraf@2.6.2
2475 silly saveTree │ ├─┬ rxjs@5.5.8
2475 silly saveTree │ │ └── symbol-observable@1.0.1
2475 silly saveTree │ ├── serialize-javascript@1.4.0
2475 silly saveTree │ ├── source-map@0.6.1
2475 silly saveTree │ └─┬ typed-rest-client@1.0.7
2475 silly saveTree │   ├── tunnel@0.0.4
2475 silly saveTree │   └── underscore@1.8.3
2475 silly saveTree ├── swagger-ui-express@2.0.15
2475 silly saveTree ├── xml-js@1.6.2
2475 silly saveTree ├── xmljs@0.3.2
2475 silly saveTree └── z85@0.0.2
2476 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
2477 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
2478 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
2478 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
2478 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
2478 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
2479 warn optional SKIPPING OPTIONAL DEPENDENCY: iltorb@1.3.10 (node_modules/iltorb):
2480 warn optional SKIPPING OPTIONAL DEPENDENCY: iltorb@1.3.10 install: `detect-libc prebuild-install || node-gyp rebuild`
2480 warn optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
2481 verbose optional SKIPPING OPTIONAL DEPENDENCY:
2481 verbose optional Failed at the iltorb@1.3.10 install script.
2481 verbose optional SKIPPING OPTIONAL DEPENDENCY: This is probably not a problem with npm. There is likely additional logging output above.
2482 verbose stack Error: libxmljs@0.18.7 install: `node-pre-gyp install --fallback-to-build --loglevel http`
2482 verbose stack Exit status 1
2482 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
2482 verbose stack     at EventEmitter.emit (events.js:180:13)
2482 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
2482 verbose stack     at ChildProcess.emit (events.js:180:13)
2482 verbose stack     at maybeClose (internal/child_process.js:936:16)
2482 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
2483 verbose pkgid libxmljs@0.18.7
2484 verbose cwd /home/work/odp/webroot/hema
2485 verbose Linux 2.6.32_1-16-0-0_virtio
2486 verbose argv "/usr/bin/node" "/usr/bin/npm" "install"
2487 verbose node v9.10.1
2488 verbose npm  v5.6.0
2489 error code ELIFECYCLE
2490 error errno 1
2491 error libxmljs@0.18.7 install: `node-pre-gyp install --fallback-to-build --loglevel http`
2491 error Exit status 1
2492 error Failed at the libxmljs@0.18.7 install script.
2492 error This is probably not a problem with npm. There is likely additional logging output above.
2493 verbose exit [ 1, true ]

**Comment by ShinChven** [comment]
I have the same issue.

**Comment by dcartman** [comment]
Same issue.

docker image: unbent 14.04
nodes: 6.9.4

I would love a workaround for this one.

**Comment by rchipka** [comment]
This will be fixed once #507 is updated and merged in

**Comment by tuananh** [comment]
@rchipka can you make a new release to see if it's fixed for this and #506 ?
