### ISSUE TITLE
Binary 404 during install: node-v57-win32-x64.tar.gz

### ISSUE THREAD

**Issue by jhdevuk** [libxmljs/libxmljs#509]
Hi,

I've just noticed our CLI build is broken due to a binary required via an npm package not being present in 0.18.8

We've noticed this before, is there any way to mitigate this for the future as it's caused quite alot of issues for us.

```
[Step 3/10] node-pre-gyp http GET https://github.com/libxmljs/libxmljs/releases/download/v0.18.8/node-v57-win32-x64.tar.gz
[10:13:56][Step 3/10] node-pre-gyp http 404 https://github.com/libxmljs/libxmljs/releases/download/v0.18.8/node-v57-win32-x64.tar.gz
[10:13:56][Step 3/10] node-pre-gyp ERR! Tried to download(404): https://github.com/libxmljs/libxmljs/releases/download/v0.18.8/node-v57-win32-x64.tar.gz 
[10:13:56][Step 3/10] node-pre-gyp ERR! Pre-built binaries not found for libxmljs@0.18.8 and node@8.9.4 (node-v57 ABI, unknown) (falling back to source compile with node-gyp) 
[10:13:56][Step 3/10] node-pre-gyp http 404 status code downloading tarball https://github.com/libxmljs/libxmljs/releases/download/v0.18.8/node-v57-win32-x64.tar.gz 
[10:13:59][Step 3/10] gyp ERR! build error 
```

Thanks

@sprsquish @defunctzombie @polotek

**Comment by lokkeshjaya** [comment]
Stuck on this issue from the morning.
As a temporary walkaround, fixing the libxmljs version to **"libxmljs": "0.18.7"** in package.json unblocks our work today. 
Hoping for a fix soon!

**Comment by sebastiankessel** [comment]
We're having the exact same problem, but libxmljs is inside of a dependency and we cannot hardcode back to older version. Any quick fix will be much appreciated!

**Comment by jhdevuk** [comment]
We're using `gulp-xml-transformer` which has a dependency on this.

**Comment by rchipka** [comment]
@tuananh That does seem to be the case. Would you know how to conditionally require different package versions for different Node environments?

We should also deprecate 0.10 and 0.12 in AppVeyor.

There also seems to be an issue with `node-pre-gyp` v0.10.0 on newer Node versions.
https://ci.appveyor.com/project/rchipka/libxmljs/branch/master/job/32u7bek84i8b4tit

`node-pre-gyp ERR! Completion callback never invoked!`

Maybe we force it to stay on 0.9.x?

**Comment by rchipka** [comment]
If someone wants to create a quick PR to remove Node 0.10/0.12 in AppVeyor config and change `package.json` so that `node-pre-gyp` semver uses `~` and not `^`, then we might be able to push a quick fix for newer node versions on Windows.

For older Node versions, we'll have to figure out how to lock in the older es5-compatible package versions.

**Comment by rchipka** [comment]
Adding v0.18.7 Windows build assets to the latest release. Not sure if this will actually work, but it's worth a shot.

**Comment by tuananh** [comment]
@rchipka i just submitted a PR for this
