### ISSUE TITLE
Pre-built binaries in 0.18.8 are not installable

### ISSUE THREAD

**Issue by rbscott** [libxmljs/libxmljs#514]
Hello,

I have been looking at this for a little while and I think despite building pre-built binaries for a number of architectures, they are not usable by NPM. I think there is a [bug](https://github.com/mapbox/node-pre-gyp/pull/371) in the version of node-pre-gyp that is used in libxmljs version 0.18.8 (0.9.1).

In node-pre-gyp 0.9.1, the command was including everything inside of the sibling directories of the build path. So even though it should include `build/Release/*`, the package actually includes `build/*`. You can see this in all of the archives that are downloaded.

This bug causes two issues:

1. It makes the tar.gz uninstallable because of another bug during installation where the untarring function doesn't create intermediate folders (it only creates files) .
1. It makes the binary distribution very [large](https://github.com/libxmljs/libxmljs/issues/484).

You can reproduce this by:

```
mkdir libxmljstest
cd libxmljstest
npm install --save libxmljs@'^0.18.8'

> libxmljs@0.18.8 install /export/node_modules/libxmljs
> node-pre-gyp install --fallback-to-build --loglevel http

node-pre-gyp http GET https://github.com/libxmljs/libxmljs/releases/download/v0.18.8/node-v57-linux-x64.tar.gz
node-pre-gyp http 302 https://github.com/libxmljs/libxmljs/releases/download/v0.18.8/node-v57-linux-x64.tar.gz
node-pre-gyp http 200 https://github.com/libxmljs/libxmljs/releases/download/v0.18.8/node-v57-linux-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not installable for libxmljs@0.18.8 and node@8.10.0 (node-v57 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp ERR! Hit error ENOTDIR: Cannot cd into '/export/node_modules/libxmljs/build/Release' 

<Source build follows>
```

Even though the binary is available for this architecture, it refuses to use the binary. I noticed that in later releases libxmljs downgraded to node-pre-gyp ~0.6.37. Not sure if this has the same bug, but I suspect it does. I think I have a fix, but wanted to check first to see if I was missing something.

```
# cat /etc/issue
Ubuntu 18.04 LTS \n \l
# node --version
v8.10.0
# npm --version
3.5.2
```

**Comment by wintergithub** [comment]
same here：

CentOS release 4.3 (Final)
Node v8.11.1
npm 5.8.0

**Comment by rbscott** [comment]
It looks like someone else already updated this https://github.com/libxmljs/libxmljs/pull/523. I think this should be closed out now.

I just tried on node 8 and node 10 and both installs worked.
