### ISSUE TITLE
Vulnerabilities in libxmljs

### ISSUE THREAD

**Issue by philippschladitz** [libxmljs/libxmljs#517]
I would like to use libxmljs for xsd-schema validation but after I installed libxmljs and ran npm audit, the following vulnerabilities were found:

hoek: Prototype pollution
Patched in: >= 5.0.3

**Comment by pkestefran** [comment]
Seems it comes through node-pre-gyp, they dropped hawk and updated require.

**Comment by sntran** [comment]
Do you plan to publish to NPM?

**Comment by rchipka** [comment]
Done
