### ISSUE TITLE
Element.find returns Elements, documentation says it should be Nodes

### ISSUE THREAD

**Issue by denkristoffer** [libxmljs/libxmljs#538]
👋 

When I use `Element.find()` I get an array of Elements back, but [the documentation says it should return nodes](https://github.com/libxmljs/libxmljs/wiki/Element#elementfindxpath). Is the problem with the docs or is this just something specific to the Element I'm using `.find()` on?

```js
const elements = root.find('//span')

elements.forEach(element => {
  console.log(element instanceof libxmljs.Element) // => true 
  console.log(element.type()) // => element
})

**Comment by Noderino** [comment]
https://github.com/libxmljs/libxmljs/blob/master/lib/document.js#L38 says find() and get() return Element not Node. 
@rchipka Can you please update docs. I am having issues with Typescript declarations. I want to update definitions but docs are not clear.
