### ISSUE TITLE
Add pre-built packages for node v67+

### ISSUE THREAD

**Issue by bkimminich** [libxmljs/libxmljs#544]
:warning: For Node 11.x no pre-built package `v67` is available.

:warning: For Node 12.x no pre-built package `v72` is available.

:question: Seeing that the last release being from August 2018: Is it planned to add those or any future versions to `libxmljs`?

**Comment by matth-c3** [comment]
Hello @bkimminich , do you know when it will be compatible on node v11 ? I have an error during the build 

```
> node-gyp rebuild

  CXX(target) Release/obj.target/xmljs/src/libxmljs.o
../src/libxmljs.cc:69:17: error: no member named 'IsDead' in 'v8::V8'
    if (v8::V8::IsDead())
        ~~~~~~~~^
1 error generated.
make: *** [Release/obj.target/xmljs/src/libxmljs.o] Error 1
```

thanks by advance

**Comment by bkimminich** [comment]
Do we have to consider `libxmljs` dead? Does anyone know of a maintained fork or an alternate library with the same capabilities?

**Comment by marudor** [comment]
v67 is supported by https://www.npmjs.com/package/libxmljs2
v72 not yet due to gyp problems.

**Comment by bkimminich** [comment]
@marudor Unfortunately it does not work as a drop in replacement for me...

```
Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /home/travis/build/bkimminich/juice-shop/node_modules/libxmljs2/build/Release/xmljs.node)
```

https://travis-ci.org/bkimminich/juice-shop/builds/535071336?utm_medium=notification&utm_source=email

**Comment by marudor** [comment]
Please create an issue at my forked repo. It's a linking problem.

**Comment by marudor** [comment]
Update for anyone interested: now supports v67 and v72.
