### ISSUE TITLE
Support Node version 10 for Windows

### ISSUE THREAD

**Issue by joem5815** [libxmljs/libxmljs#547]
It looks like builds don't exist for Node 10.x for Windows. It looks like this was an issue addressed last year by #507 , but looking at the releases page it does look like these builds are missing, which is causing the same 404 issues when building packages dependent on libxmljs.

**Comment by corvinrok** [comment]
@joem5815 , just wondering what version of Node 10 are you using? It seems to be working at least on Windows 7 with Node **10.15.3**. I just tried it right now to be sure, and the following binaries were loaded successfully for version **0.19.5** of **`libxmljs`**.

```
C:\git\widget-master\server-side>npm install

> libxmljs@0.19.5 install C:\git\widget-master\server-side\node_modules\libxmljs
> node-pre-gyp install --fallback-to-build --loglevel http

node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp http GET https://github.com/libxmljs/libxmljs/releases/download/v0.19.5/node-v64-win32-x64.tar.gz
node-pre-gyp http 200 https://github.com/libxmljs/libxmljs/releases/download/v0.19.5/node-v64-win32-x64.tar.gz
[libxmljs] Success: "C:\git\widget-master\server-side\node_modules\libxmljs\build\Release\xmljs.node" is installed via remote
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN server-side@0.0.0 No repository field.
npm WARN server-side@0.0.0 No license field.

added 500 packages from 858 contributors and audited 1334 packages in 21.671s
```

As you can see above, that seems to be working fine.

Actually, this library is also compiling on Node 11 as well (although it needs to recompile on my local machine with windows-build-tools). The Node 10.x versions seemed to download the precompiles for me, but maybe it was only on specific version of Node I happened to be using. At least for version 10.15.3 it seems to have the precompiled binaries ready to download.

**Comment by joem5815** [comment]
@corvinrok Sorry, missed an important detail there. This only affects building packages that require libxmljs 18.x. The 19.x versions do have the Windows builds, but they are missing for libxmljs 18.x running with Node 10.x.

**Comment by corvinrok** [comment]
@joem5815 you might consider just tweaking the issue title to reflect you are dealing specifically with libxmljs 18.x only... (not sure if it will help inspire a resolution or not :) )..
