### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by BinniZenobioCordovaLeandro** [libxmljs/libxmljs#551]
Hi, when a use `npm install libxmljs` return thisi message.

> 
> 
> > libxmljs@0.19.5 install C:\xampp\htdocs\soap-server\node_modules\libxmljs
> > node-pre-gyp install --fallback-to-build --loglevel http
> 
> node-pre-gyp WARN Using request for node-pre-gyp https download
> node-pre-gyp http GET https://github.com/libxmljs/libxmljs/releases/download/v0.19.5/node-v67-win32-x64.tar.gz
> node-pre-gyp http 404 https://github.com/libxmljs/libxmljs/releases/download/v0.19.5/node-v67-win32-x64.tar.gz
> node-pre-gyp WARN Tried to download(404): https://github.com/libxmljs/libxmljs/releases/download/v0.19.5/node-v67-win32-x64.tar.gz
> node-pre-gyp WARN Pre-built binaries not found for libxmljs@0.19.5 and node@11.9.0 (node-v67 ABI, unknown) (falling back to source compile with node-gyp)
> node-pre-gyp http 404 status code downloading tarball https://github.com/libxmljs/libxmljs/releases/download/v0.19.5/node-v67-win32-x64.tar.gz
> Los proyectos de esta solución se van a compilar de uno en uno. Para habilitar la compilación en paralelo, agregue el modificador "/m".
> C:\xampp\htdocs\soap-server\node_modules\libxmljs\build\xmljs.vcxproj(20,3): error MSB4019: No se encuentra el proyecto importado "C:\Microsoft.Cpp.Default.props". Asegúrese de que la ruta
>  de acceso de la declaración <Import> es correcta y de que el archivo se encuentra en el disco.
> gyp ERR! build error
> gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
> gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
> gyp ERR! stack     at ChildProcess.emit (events.js:197:13)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
> gyp ERR! System Windows_NT 10.0.17134
> gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--loglevel=http" "--module=C:\\xampp\\htdocs\\soap-server\\node_modules\\libxmljs\\build\\Release\\xmljs.node" "--module_name=xmljs" "--module_path=C:\\xampp\\htdocs\\soap-server\\node_modules\\libxmljs\\build\\Release" "--napi_version=4" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v67"
> gyp ERR! cwd C:\xampp\htdocs\soap-server\node_modules\libxmljs
> gyp ERR! node -v v11.9.0
> gyp ERR! node-gyp -v v3.8.0
> gyp ERR! not ok
> node-pre-gyp ERR! build error
> node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --loglevel=http --module=C:\xampp\htdocs\soap-server\node_modules\libxmljs\build\Release\xmljs.node --module_name=xmljs --module_path=C:\xampp\htdocs\soap-server\node_modules\libxmljs\build\Release --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v67' (1)
> node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\xampp\htdocs\soap-server\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
> node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:197:13)
> node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:978:16)
> node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
> node-pre-gyp ERR! System Windows_NT 10.0.17134
> node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\xampp\\htdocs\\soap-server\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build" "--loglevel"
> "http"
> node-pre-gyp ERR! cwd C:\xampp\htdocs\soap-server\node_modules\libxmljs
> node-pre-gyp ERR! node -v v11.9.0
> node-pre-gyp ERR! node-pre-gyp -v v0.11.0
> node-pre-gyp ERR! not ok
> Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --loglevel=http --module=C:\xampp\htdocs\soap-server\node_modules\libxmljs\build\Release\xmljs.node --module_name=xmljs --module_path=C:\xampp\htdocs\soap-server\node_modules\libxmljs\build\Release --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v67' (1)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! libxmljs@0.19.5 install: `node-pre-gyp install --fallback-to-build --loglevel http`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the libxmljs@0.19.5 install script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\bcordova\AppData\Roaming\npm-cache\_logs\2019-06-04T17_58_18_946Z-debug.log

I thinking on this line, because the link not exists when i shared.
> node-pre-gyp http 404 https://github.com/libxmljs/libxmljs/releases/download/v0.19.5/node-v67-win32-x64.tar.gz

anyone have any idea ?, or a solution to this.

**Comment by kyob** [comment]
Same problem:
```bash
# npm install libxmljs

> libxmljs@0.19.5 install /opt/genieacs/node_modules/libxmljs
> node-pre-gyp install --fallback-to-build --loglevel http

node-pre-gyp WARN Using needle for node-pre-gyp https download 
node-pre-gyp http GET https://github.com/libxmljs/libxmljs/releases/download/v0.19.5/node-v72-linux-x64.tar.gz
node-pre-gyp http 404 https://github.com/libxmljs/libxmljs/releases/download/v0.19.5/node-v72-linux-x64.tar.gz
node-pre-gyp WARN Tried to download(404): https://github.com/libxmljs/libxmljs/releases/download/v0.19.5/node-v72-linux-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for libxmljs@0.19.5 and node@12.4.0 (node-v72 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp http 404 status code downloading tarball https://github.com/libxmljs/libxmljs/releases/download/v0.19.5/node-v72-linux-x64.tar.gz 


# curl -I https://github.com/libxmljs/libxmljs/releases/download/v0.19.5/node-v72-linux-x64.tar.gz
HTTP/1.1 404 Not Found
Date: Fri, 21 Jun 2019 08:41:25 GMT
Content-Type: text/plain; charset=utf-8
Server: GitHub.com
Status: 404 Not Found
```

**Comment by philippzentner** [comment]
push

**Comment by Cameron637** [comment]
Related to https://github.com/libxmljs/libxmljs/issues/549#issuecomment-498248651

**Comment by DanielRuf** [comment]
They use NodeJS 11. This is not the problem. If there is no prebuilt version node-gyp creates one from source.

If you are on Windows try `npm i -g windows-build-tools`.

**Comment by DanielRuf** [comment]
> Error MSB4019: The imported project "C: \ Microsoft.Cpp.Default.props" is not found. Make sure the route
Access statement is correct and that the file is on disk.

Please try to install the needed tools as I wrote in my last comment. You may have not the needed build dependencies.
