### ISSUE TITLE
Array "instanceof" issue in libxml.Document && libxml.Element get function.

### ISSUE THREAD

**Issue by fayzzzm** [libxmljs/libxmljs#566]
Hey, **LibxmlJS team**,
Due to the issue of `instanceof Array` in nodeJS (Link: https://github.com/facebook/jest/issues/2549), some times `get` function returns an array, instead of `array[0]`. After a couple of researches, I found out, `instanceof Array` in `get` function doesn't work properly in several cases and I'd changed it to `Array.isArray(res)`, now it works fine. 

**Examle of fixed issue code:**
```
libxml.Document.prototype.get = function() {
    const res = this.find.apply(this, arguments);
    if (Array.isArray(res)) {
        return res[0];
    } else {
        return res;
    }
};
```
Could you look at this issue and tackle this problem, due others wouldn't have this problem. 

Best regards, **fayzzz**

**Comment by marudor** [comment]
There is a PR for this since 2017. This repo is mainly dead.
This is fixed in my fork (as well as several other things)
https://github.com/marudor/libxmljs2

**Comment by fayzzzm** [comment]
Thanks for reply @marudor
