### ISSUE TITLE
Doesn't build on windows 10 for target electron (7.1.11 and 8.0.0)

### ISSUE THREAD

**Issue by TanninOne** [libxmljs/libxmljs#567]
Since there are no prebuild binaries for electron libxmljs gets rebuilt during yarn install.
This used to work with electron 4, not sure why or why it stopped working.

The error message is 
`LINK : fatal error LNK1194: cannot delay-load 'node.exe' due to import of data symbol '"__declspec(dllimport) const v8::ArrayBuffer::Allocator::`vftable'" (__imp_??_7Allocator@ArrayBuffer@v8@@6B@)'; link without /DELAYLOAD:node.exe [c:\Work\vortex\node_module s\libxmljs\build\xmljs.vcxproj]`

Now with electron afaik it has to be delay-loaded because electron.exe has nodejs statically linked in so it takes over that role.
Besides, the export of ArrayBuffer::Allocator shouldn't be necessary as far as I understand.

After a lot of digging I found that in the binding.sln file that node-gyp generates, the macro BUILDING_NODE_EXTENSION isn't defined which (as far as I understand it) is supposed to be defined and it _would_ have suppressed the export of ArrayBuffer allowing the build to work.

Unfortunately I have no clue why that macro isn't defined, I thought node-gyp was supposed to do that automatically (through addon.gypi) - no clue why it doesn't do it for libxmljs (or at least for the Release build because the macro _is_ defined in the debug build).

**Comment by tobias-klein** [comment]
I'm also facing the same issue.

**Comment by marudor** [comment]
My fork should work on windows electron. (https://github.com/marudor/libxmljs2)

**Comment by sdwinne** [comment]
@marudor , with libxmljs2 I see the same errors when running electron-rebuild.

**Comment by MrMYHuang** [comment]
[deleted]
> The error message is
> `LINK : fatal error LNK1194: cannot delay-load 'node.exe' due to import of data symbol '"__declspec(dllimport) const v8::ArrayBuffer::Allocator::`vftable'" (__imp_??_7Allocator@ArrayBuffer@v8@@6b@)'; link without /DELAYLOAD:node.exe [c:\Work\vortex\node_module s\libxmljs\build\xmljs.vcxproj]`
>
[deleted] 
> After a lot of digging I found that in the binding.sln file that node-gyp generates, the macro BUILDING_NODE_EXTENSION isn't defined which (as far as I understand it) is supposed to be defined and it _would_ have suppressed the export of ArrayBuffer allowing the build to work.

Thanks, @TanninOne . I fix this problem by modifying binding.gyp and adding BUILDING_NODE_EXTENSION define for OS=="win".
https://github.com/MrMYHuang/libxmljs/blob/c12974c30ece15075dcfacc92a84b8d35f88ba7c/binding.gyp#L82-L86
