### ISSUE TITLE
Error when install libxmljs (ubuntu 18.04)

### ISSUE THREAD

**Issue by hungnt151** [libxmljs/libxmljs#569]
Hi everyone,
Can you please help me to fix this issue?

npm install libxmljs

> libxmljs@0.19.7 install /home/hung/Desktop/hh3-web/node_modules/libxmljs
> node-pre-gyp install --fallback-to-build --loglevel http

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp http GET https://github.com/libxmljs/libxmljs/releases/download/v0.19.7/node-v47-linux-x64.tar.gz
node-pre-gyp http 200 https://github.com/libxmljs/libxmljs/releases/download/v0.19.7/node-v47-linux-x64.tar.gz
node-pre-gyp ERR! UNCAUGHT EXCEPTION 
node-pre-gyp ERR! stack TypeError: this is not a typed array.
node-pre-gyp ERR! stack     at Function.from (native)
node-pre-gyp ERR! stack     at Unzip.write (/home/hung/Desktop/hh3-web/node_modules/minizlib/index.js:167:42)
node-pre-gyp ERR! stack     at Unpack.write (/home/hung/Desktop/hh3-web/node_modules/node-pre-gyp/node_modules/tar/lib/parse.js:305:58)
node-pre-gyp ERR! stack     at Request.ondata (stream.js:31:26)
node-pre-gyp ERR! stack     at emitOne (events.js:90:13)
node-pre-gyp ERR! stack     at Request.emit (events.js:182:7)
node-pre-gyp ERR! stack     at IncomingMessage.<anonymous> (/home/hung/Desktop/hh3-web/node_modules/request/main.js:591:14)
node-pre-gyp ERR! stack     at emitOne (events.js:90:13)
node-pre-gyp ERR! stack     at IncomingMessage.emit (events.js:182:7)
node-pre-gyp ERR! stack     at readableAddChunk (_stream_readable.js:153:18)
node-pre-gyp ERR! System Linux 5.3.0-40-generic
node-pre-gyp ERR! command "/home/hung/.nvm/versions/node/v5.9.0/bin/node" "/home/hung/Desktop/hh3-web/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--loglevel" "http"
node-pre-gyp ERR! cwd /home/hung/Desktop/hh3-web/node_modules/libxmljs
node-pre-gyp ERR! node -v v5.9.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! This is a bug in `node-pre-gyp`.
node-pre-gyp ERR! Try to update node-pre-gyp and file an issue if it does not help:
node-pre-gyp ERR!     <https://github.com/mapbox/node-pre-gyp/issues>
npm ERR! Linux 5.3.0-40-generic
npm ERR! argv "/home/hung/.nvm/versions/node/v5.9.0/bin/node" "/home/hung/.nvm/versions/node/v5.9.0/bin/npm" "install" "libxmljs"
npm ERR! node v5.9.0
npm ERR! npm  v3.7.3
npm ERR! code ELIFECYCLE

npm ERR! libxmljs@0.19.7 install: `node-pre-gyp install --fallback-to-build --loglevel http`
npm ERR! Exit status 7
npm ERR! 
npm ERR! Failed at the libxmljs@0.19.7 install script 'node-pre-gyp install --fallback-to-build --loglevel http'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the libxmljs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build --loglevel http
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs libxmljs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls libxmljs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/hung/Desktop/hh3-web/npm-debug.log

**Comment by AHoxha19** [comment]
Same error 🖐

**Comment by fayzzzm** [comment]
# before installing node-gyp on windows
npm install --global --production windows-build-tools

# install node-gyp globally
npm install -g node-gyp

And also check your node js version. At least it should be latest.
