### ISSUE TITLE
Please add binary for v0.19.7/node-v79-linux-x64.tar.gz

### ISSUE THREAD

**Issue by amotzte** [libxmljs/libxmljs#582]
> node-pre-gyp install --fallback-to-build --loglevel http

[91mnode-pre-gyp[0m[91m WARN Using needle for node-pre-gyp https download 
[0m[91mnode-pre-gyp http GET https://github.com/libxmljs/libxmljs/releases/download/v0.19.7/node-v79-linux-x64.tar.gz
[0m[91mnode-pre-gyp http 404 https://github.com/libxmljs/libxmljs/releases/download/v0.19.7/node-v79-linux-x64.tar.gz
[0m[91mnode-pre-gyp WARN Tried to download(404): https://github.com/libxmljs/libxmljs/releases/download/v0.19.7/node-v79-linux-x64.tar.gz 
[0m[91mnode-pre-gyp WARN Pre-built binaries not found for libxmljs@0.19.7 and node@13.14.0 (node-v79 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp http [0m[91m404 status code downloading tarball https://github.com/libxmljs/libxmljs/releases/download/v0.19.7/node-v79-linux-x64.tar.gz

**Comment by ElijahLynn** [comment]
I seem to be having a similar issue as well with the script wanting: 
> https://github.com/libxmljs/libxmljs/releases/download/v0.19.7/node-v83-linux-x64.tar.gz

Still digging into it.

**Comment by marudor** [comment]
This repository is mainly unmaintained. I maintain a fork here: https://github.com/marudor/libxmljs2
I do not support node 13 anymore though. (As it is end of life)
You would need to switch to node 12 or node 14. (I only support non End of life node versions)

**Comment by ElijahLynn** [comment]
> This repository is mainly unmaintained. I maintain a fork here: https://github.com/marudor/libxmljs2
> I do not support node 13 anymore though. (As it is end of life)
> You would need to switch to node 12 or node 14. (I only support non End of life node versions)

Thanks for letting me know about this!!

> `npm install libxmljs2`

**Comment by tuananh** [comment]
@ElijahLynn should be fixed in 0.19.8
