### ISSUE TITLE
Failing to build

### ISSUE THREAD

**Issue by Milo123459** [libxmljs/libxmljs#587]
Hi, I have python2.7 installed via windows-build-tools and I get this error:
npm ERR! node-pre-gyp http 404 status code downloading tarball https://github.com/libxmljs/libxmljs/releases/download/v0.19.7/node-v88-win32-x64.ta
r.gz

It can't be downloaded? Very odd

**Comment by Davidiusdadi** [comment]
i can confirm the error on ` Ubuntu 20.04.2 LTS`
```
node-pre-gyp http 404 https://github.com/libxmljs/libxmljs/releases/download/v0.19.7/node-v83-linux-x64.tar.gz
```

I noticed the error because after the `404` the package will try to build from source which was failing as well in my case because my `python` command was missing.

I managed to get my `yarn install` working by installing python2 via `apt install python2`

**Comment by mgaert** [comment]
Same issue!.

```
error node-pre-gyp http 404 https://github.com/libxmljs/libxmljs/releases/download/v0.19.7/node-v93-win32-x64.tar.gz
error node-pre-gyp WARN Tried to download(404): https://github.com/libxmljs/libxmljs/releases/download/v0.19.7/node-v93-win32-x64.tar.gz
error node-pre-gyp WARN Pre-built binaries not found for libxmljs@0.19.7 and node@16.13.1 (node-v93 ABI, unknown) (falling back to source compile with node-gyp)
error node-pre-gyp http 404 status code downloading tarball https://github.com/libxmljs/libxmljs/releases/download/v0.19.7/node-v93-win32-x64.tar.gz
error gyp ERR! build error
```

**Comment by code4cbe** [comment]
I am also getting same issue. Any fix or solution for this?

**Comment by cando-jo** [comment]
Any fixes?
