### ISSUE TITLE
Errors installing v0.19.10

### ISSUE THREAD

**Issue by joshmc82** [libxmljs/libxmljs#601]
Errors trying to install:
`npm ERR! Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --loglevel=http --module=/Users/josh/node_modules/libxmljs/build/Release/xmljs.node --module_name=xmljs --module_path=/Users/josh/node_modules/libxmljs/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
npm ERR! node-pre-gyp http GET https://github.com/libxmljs/libxmljs/releases/download/v0.19.10/node-v93-darwin-arm64.tar.gz
npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/libxmljs/libxmljs/releases/download/v0.19.10/node-v93-darwin-arm64.tar.gz
npm ERR! node-pre-gyp WARN Pre-built binaries not installable for libxmljs@0.19.10 and node@16.15.0 (node-v93 ABI, unknown) (falling back to source compile with node-gyp)
npm ERR! node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/libxmljs/libxmljs/releases/download/v0.19.10/node-v93-darwin-arm64.tar.gz`

**Comment by tuananh** [comment]
@joshmc82 looks like it's fixed here: https://github.com/libxmljs/libxmljs/pull/600

just need a new release cut.
