### ISSUE TITLE
issue with 1.0.0 release

### ISSUE THREAD

**Issue by tuananh** [libxmljs/libxmljs#613]
i try with 1.0.0 release and got the following issue

```
Error: Cannot find module '/tmp/libxmljs/node_modules/libxmljs/dist/index.js'. Please verify that the package.json has a valid "main" entry
```

this is the content of libxmljjs's `package.json`

```
"main": "dist/index.js",
  "types": "dist/index.d.ts",
```

looks like `dist` is being ignore during npm publish?

@rchipka

**Comment by rchipka** [comment]
@tuananh Thanks for catching this! Can you try v1.0.1?
