### ISSUE TITLE
use .npmignore to exclude certains file/folders in vendor to reduce published size?

### ISSUE THREAD

**Issue by tuananh** [libxmljs/libxmljs#616]
![image](https://user-images.githubusercontent.com/627278/229311090-6cf5e769-571f-4f1b-b37d-38a149997838.png)

it's a whooping 43MB right now which mostly come from vendor/libxml2 folder.

test: 8.8MB
doc: 13MB
result: 15MB

we probably dont need all these to compile right, @rchipka ?

**Comment by rchipka** [comment]
lol i tried, see https://github.com/libxmljs/libxmljs/issues/614

**Comment by rchipka** [comment]
i really didn't want to include vendor/libxml2, but getting submodules to init before building turns out to be an absolute nightmare

**Comment by rchipka** [comment]
@mureinik can attest to this. if anyone has any other ideas i'm definitely still open to paring down the npm package.

**Comment by tuananh** [comment]
What i mean is we still include `libxml2` in vendor but add those folders (test/doc/result) to `.npmignore` so we dont publish those folder to npm?

**Comment by rchipka** [comment]
https://www.npmjs.com/package/libxmljs?activeTab=code

`test/` is still included

are you suggesting we add libxml2 to .npmignore? that's exactly what we experimented with in #614

**Comment by tuananh** [comment]
![image](https://user-images.githubusercontent.com/627278/229312365-c2118ec2-70bf-4171-8a75-6b5fa14b60c6.png)

`npm publish --dry-run`

![image](https://user-images.githubusercontent.com/627278/229312384-67497a15-8eea-419e-af03-a7218f01a445.png)


vs before the change

![image](https://user-images.githubusercontent.com/627278/229312394-7ab20a44-295d-44d2-98ba-77d0e10c9e5c.png)

**Comment by mureinik** [comment]
libxmljs most definitely need to pack the vendored libxml in order to allow building from source, but actually, as this bug states, we don't need *all* of it.\
It's a bit of scut-work, but it's a one time, and there's a lot of stuff there we can explicitly add to `.npmignore`. #617 is my take on this.

**Comment by tuananh** [comment]
This is what im talking about :). Thanks 

Its a bit hard to ask upstream to do a packed release
