### ISSUE TITLE
Invalid schema

### ISSUE THREAD

**Issue by Philomath88** [libxmljs/libxmljs#624]
Hey,

I am trying to validate my xml against this schema: https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Product.xsd

But I get an invalid schema error. 

I have also tried to programmatically remove the include statements to no avail.

Happy to offer 50 Euro if someone can help me.

**Comment by fabianobonomini** [comment]
@Philomath88  have you solve this issue?

**Comment by Philomath88** [comment]
@fabianobonomini Yes, I did - will close the issue

**Comment by fabianobonomini** [comment]
can you please give mi some infos how you solve this problem? thanks

**Comment by Philomath88** [comment]
@fabianobonomini That's my code. Hope it helps: 

`async function validateXML(xmlString) {
  return new Promise((resolve, reject) => {
    // Save the resolved schema to a file named 'compiled_schema.xsd' in the 'schemas' directory
    const compiledSchemaPath = path.join(__dirname, 'schemas', 'compiled_schema.xsd');

    const resolvedSchemaWithAbsolutePaths = resolveIncludes(schemaString, './schemas', mainSchemaFilePath);

    // Write the resolved schema to the file
    fs.writeFileSync(compiledSchemaPath, resolvedSchemaWithAbsolutePaths);

    // spawn the xmllint process with the right arguments
    const xmllint = spawn('xmllint', ['--schema', compiledSchemaPath, '--noout', '-']);

    let errorOutput = '';

    // Write the XML content to xmllint stdin
    xmllint.stdin.write(xmlString);
    xmllint.stdin.end();

    xmllint.stderr.on('data', (data) => {
      errorOutput += data.toString();
    });

    xmllint.on('close', (code) => {
      if (code === 0) {
        resolve('Validation succeeded!');
      } else {
        reject(`Validation failed with code ${code}:\n${errorOutput}`);
      }
    });

    xmllint.on('error', (error) => {
      reject(`Error executing xmllint: ${error}`);
    });
  });
}


function resolveIncludes(xml, schemasDir) {
  let updatedXml = xml;

  const includeRegex = /<xs:include\s+schemaLocation="([^"]+)"\s*\/>/ig;
  let match;

  console.log("[resolveIncludes] Processing XML");


  while ((match = includeRegex.exec(xml))) {
    const includePath = match[1];
    const basePath = path.join(__dirname, schemasDir);
    const includeFullPath = url.resolve(basePath, includePath);

    if (!fs.existsSync(includeFullPath)) {
      console.warn(`[resolveIncludes] File not found: ${includeFullPath}`);
      continue;
    }

    const includeXml = fs.readFileSync(includeFullPath, 'utf8');
    const resolvedXml = resolveIncludes(includeXml, basePath);

    updatedXml = updatedXml.replace(match[0], resolvedXml);
  }

  return updatedXml;
}`
