### ISSUE TITLE
version 1.0.10 doesn't work on Mac

### ISSUE THREAD

**Issue by orept** [libxmljs/libxmljs#637]
Throws
`Error: dlopen(/.../node_modules/libxmljs/build/Release/xmljs.node, 0x0001): tried: '/.../node_modules/libxmljs/build/Release/xmljs.node' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/.../node_modules/libxmljs/build/Release/xmljs.node' (no such file), '/.../node_modules/libxmljs/build/Release/xmljs.node' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))`

Can be fixed by downgrading to previous `1.0.9`

**Comment by ableda** [comment]
I am also seeing the same behaviour. Thank you for opening the issue
