### ISSUE TITLE
implement .toJSON() method

### ISSUE THREAD

**Issue by oroce** [libxmljs/libxmljs#93]
With toJSON() method debugging would be simpler.

**Comment by danielb2** [comment]
It would be awesome if the examples provided a way to convert XML to JSON then at least. @defunctzombie  you mention other libraries which do it, are there any which uses this library you can point to?

**Comment by defunctzombie** [comment]
https://github.com/buglabs/node-xml2json

**Comment by danielb2** [comment]
:+1:
